/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ProjetoFinal;

import GUIs.EstoqueGUI;
import GUIs.FinancasGUI;
import GUIs.GadosGUI;
import GUIs.VendasGUI;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author joaopcandido
 */
public class CansanvimGUI extends javax.swing.JFrame {

    /**
     * Creates new form CansanvimGUI
     */
    public CansanvimGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        DesktopPane = new javax.swing.JDesktopPane();
        jBEstoque = new javax.swing.JButton();
        jBGados = new javax.swing.JButton();
        jBVendas = new javax.swing.JButton();
        jBFinanceiro = new javax.swing.JButton();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jFileExit = new javax.swing.JMenuItem();
        jMenuFrame = new javax.swing.JMenu();
        jMenuGados = new javax.swing.JMenuItem();
        jMenuEstoque = new javax.swing.JMenuItem();
        jMenuVendas = new javax.swing.JMenuItem();
        jMenuFinanceiro = new javax.swing.JMenuItem();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jBEstoque.setText("Estoque");
        jBEstoque.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBEstoqueMouseClicked(evt);
            }
        });

        jBGados.setText("Gados");
        jBGados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBGadosMouseClicked(evt);
            }
        });

        jBVendas.setText("Vendas");
        jBVendas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBVendasMouseClicked(evt);
            }
        });

        jBFinanceiro.setText("Finanças");
        jBFinanceiro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBFinanceiroMouseClicked(evt);
            }
        });

        jMenuFile.setText("Arquivo");

        jFileExit.setText("Fechar");
        jFileExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFileExitActionPerformed(evt);
            }
        });
        jMenuFile.add(jFileExit);

        jMenuBar.add(jMenuFile);

        jMenuFrame.setText("Escolha o Setor");

        jMenuGados.setText("Gados");
        jMenuGados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuGadosActionPerformed(evt);
            }
        });
        jMenuFrame.add(jMenuGados);

        jMenuEstoque.setText("Estoque");
        jMenuEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuEstoqueActionPerformed(evt);
            }
        });
        jMenuFrame.add(jMenuEstoque);

        jMenuVendas.setText("Vendas");
        jMenuVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuVendasActionPerformed(evt);
            }
        });
        jMenuFrame.add(jMenuVendas);

        jMenuFinanceiro.setText("Finanças");
        jMenuFinanceiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuFinanceiroActionPerformed(evt);
            }
        });
        jMenuFrame.add(jMenuFinanceiro);

        jMenuBar.add(jMenuFrame);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(374, 374, 374)
                .addComponent(jBGados, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jBEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jBVendas, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jBFinanceiro, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(373, Short.MAX_VALUE))
            .addComponent(DesktopPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(DesktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, 625, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBGados, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBVendas, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBFinanceiro, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        DesktopPane.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jFileExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFileExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jFileExitActionPerformed

    private void jMenuGadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuGadosActionPerformed
        // TODO add your handling code here:
        if(!(DesktopPane.getSelectedFrame() instanceof EstoqueGUI) && !(DesktopPane.getSelectedFrame() instanceof VendasGUI) 
                && !(DesktopPane.getSelectedFrame() instanceof GadosGUI) && !(DesktopPane.getSelectedFrame() instanceof FinancasGUI)){
            GadosGUI gados = new GadosGUI();
            DesktopPane.add(gados);
            gados.setVisible(true);
            gados.setSize(1351,625);
        }
        else
            JOptionPane.showMessageDialog(rootPane, "Feche a janela aberta para abrir uma nova!");
    }//GEN-LAST:event_jMenuGadosActionPerformed

    private void jMenuEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuEstoqueActionPerformed
        // TODO add your handling code here:
        if(!(DesktopPane.getSelectedFrame() instanceof EstoqueGUI) && !(DesktopPane.getSelectedFrame() instanceof VendasGUI) 
                && !(DesktopPane.getSelectedFrame() instanceof GadosGUI) && !(DesktopPane.getSelectedFrame() instanceof FinancasGUI)){
            EstoqueGUI estoque = new EstoqueGUI();
            DesktopPane.add(estoque);
            estoque.setVisible(true);
            estoque.setSize(1351,625);
        }
        else
            JOptionPane.showMessageDialog(rootPane, "Feche a janela aberta para abrir uma nova!");
    }//GEN-LAST:event_jMenuEstoqueActionPerformed

    private void jMenuVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuVendasActionPerformed
        // TODO add your handling code here:
        if(!(DesktopPane.getSelectedFrame() instanceof EstoqueGUI) && !(DesktopPane.getSelectedFrame() instanceof VendasGUI) 
                && !(DesktopPane.getSelectedFrame() instanceof GadosGUI) && !(DesktopPane.getSelectedFrame() instanceof FinancasGUI)){
                VendasGUI vendas = new VendasGUI();
                DesktopPane.add(vendas);
                vendas.setVisible(true);
                vendas.setSize(1351,625);
        }
        else
            JOptionPane.showMessageDialog(rootPane, "Feche a janela aberta para abrir uma nova!");
    }//GEN-LAST:event_jMenuVendasActionPerformed

    private void jBGadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBGadosMouseClicked
        // TODO add your handling code here:
        if(!(DesktopPane.getSelectedFrame() instanceof EstoqueGUI) && !(DesktopPane.getSelectedFrame() instanceof VendasGUI) 
                && !(DesktopPane.getSelectedFrame() instanceof GadosGUI) && !(DesktopPane.getSelectedFrame() instanceof FinancasGUI)){
            GadosGUI gados = new GadosGUI();
            DesktopPane.add(gados);
            gados.setVisible(true);
            gados.setSize(DesktopPane.getSize());
        }
        else
            JOptionPane.showMessageDialog(rootPane, "Feche a janela aberta para abrir uma nova!");
    }//GEN-LAST:event_jBGadosMouseClicked

    private void jBEstoqueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBEstoqueMouseClicked
        // TODO add your handling code here:
        if(!(DesktopPane.getSelectedFrame() instanceof EstoqueGUI) && !(DesktopPane.getSelectedFrame() instanceof VendasGUI) 
                && !(DesktopPane.getSelectedFrame() instanceof GadosGUI) && !(DesktopPane.getSelectedFrame() instanceof FinancasGUI)){
            EstoqueGUI estoque = new EstoqueGUI();
            DesktopPane.add(estoque);
            estoque.setVisible(true);
            estoque.setSize(1351,625);
        }
        else
            JOptionPane.showMessageDialog(rootPane, "Feche a janela aberta para abrir uma nova!");
    }//GEN-LAST:event_jBEstoqueMouseClicked

    private void jBVendasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBVendasMouseClicked
        // TODO add your handling code here:
        if(!(DesktopPane.getSelectedFrame() instanceof EstoqueGUI) && !(DesktopPane.getSelectedFrame() instanceof VendasGUI) 
                && !(DesktopPane.getSelectedFrame() instanceof GadosGUI) && !(DesktopPane.getSelectedFrame() instanceof FinancasGUI)){
            VendasGUI vendas = new VendasGUI();
            DesktopPane.add(vendas);
            vendas.setVisible(true);
            vendas.setSize(1351,625);
        }
        else
            JOptionPane.showMessageDialog(rootPane, "Feche a janela aberta para abrir uma nova!");
    }//GEN-LAST:event_jBVendasMouseClicked

    private void jBFinanceiroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBFinanceiroMouseClicked
        // TODO add your handling code here:
        if(!(DesktopPane.getSelectedFrame() instanceof EstoqueGUI) && !(DesktopPane.getSelectedFrame() instanceof VendasGUI) 
                && !(DesktopPane.getSelectedFrame() instanceof GadosGUI) && !(DesktopPane.getSelectedFrame() instanceof FinancasGUI)){
            FinancasGUI finanças = new FinancasGUI();
            DesktopPane.add(finanças);
            finanças.setVisible(true);
            finanças.setSize(1351,625);
        }
        else
            JOptionPane.showMessageDialog(rootPane, "Feche a janela aberta para abrir uma nova!");
    }//GEN-LAST:event_jBFinanceiroMouseClicked

    private void jMenuFinanceiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuFinanceiroActionPerformed
        // TODO add your handling code here:
        if(!(DesktopPane.getSelectedFrame() instanceof EstoqueGUI) && !(DesktopPane.getSelectedFrame() instanceof VendasGUI) 
                && !(DesktopPane.getSelectedFrame() instanceof GadosGUI) && !(DesktopPane.getSelectedFrame() instanceof FinancasGUI)){
            FinancasGUI finanças = new FinancasGUI();
            DesktopPane.add(finanças);
            finanças.setVisible(true);
            finanças.setSize(1351,625);
        }
        else
            JOptionPane.showMessageDialog(rootPane, "Feche a janela aberta para abrir uma nova!");
    }//GEN-LAST:event_jMenuFinanceiroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CansanvimGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CansanvimGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CansanvimGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CansanvimGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CansanvimGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane DesktopPane;
    private javax.swing.JButton jBEstoque;
    private javax.swing.JButton jBFinanceiro;
    private javax.swing.JButton jBGados;
    private javax.swing.JButton jBVendas;
    private javax.swing.JMenuItem jFileExit;
    private javax.swing.JList<String> jList1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenuItem jMenuEstoque;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JMenuItem jMenuFinanceiro;
    private javax.swing.JMenu jMenuFrame;
    private javax.swing.JMenuItem jMenuGados;
    private javax.swing.JMenuItem jMenuVendas;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
