package GUIs;


import static com.sun.java.accessibility.util.AWTEventMonitor.addWindowListener;
import java.beans.PropertyVetoException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author JoãoPaulo
 */
public class EstoqueGUI extends javax.swing.JInternalFrame {

    /**
     * Creates new form EstoqueGUI
     */
    public EstoqueGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLLoteRaçaoCorte = new javax.swing.JLabel();
        jTPreçoVacinaLeite = new javax.swing.JTextField();
        jLLoteVacinaLeite = new javax.swing.JLabel();
        jTPreçoRaçaoLeite = new javax.swing.JTextField();
        jLPreçoRaçãoCorte = new javax.swing.JLabel();
        jLLoteRaçaoLeite = new javax.swing.JLabel();
        jLPreçoVacinaCorte = new javax.swing.JLabel();
        jRVacinadeCorte = new javax.swing.JRadioButton();
        jLPreçoVacinaLeite = new javax.swing.JLabel();
        jLLoteVacinaCorte = new javax.swing.JLabel();
        jTPreçoVacinaCorte = new javax.swing.JTextField();
        jTPreçoRaçaoCorte = new javax.swing.JTextField();
        jRVacinadeLeite = new javax.swing.JRadioButton();
        jTLoteRaçaoCorte = new javax.swing.JTextField();
        jTLoteVacinaLeite = new javax.swing.JTextField();
        jCDia = new javax.swing.JComboBox<>();
        jQuantidade = new javax.swing.JLabel();
        jTQuantidade = new javax.swing.JTextField();
        jLPreçoRaçaoLeite = new javax.swing.JLabel();
        jRRaçaoLeite = new javax.swing.JRadioButton();
        jCAno = new javax.swing.JComboBox<>();
        jTLoteVacinaCorte = new javax.swing.JTextField();
        jBAdicionar = new javax.swing.JButton();
        jRRaçaodeCorte = new javax.swing.JRadioButton();
        jTLoteRaçaoLeite = new javax.swing.JTextField();
        jCMes = new javax.swing.JComboBox<>();
        jLData = new javax.swing.JLabel();
        jLSeleçao = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jRRaçaoLeite1 = new javax.swing.JRadioButton();
        jLLoteVacinaCorte1 = new javax.swing.JLabel();
        jLLoteVacinaLeite1 = new javax.swing.JLabel();
        jBRemover = new javax.swing.JButton();
        jRVacinaLeite1 = new javax.swing.JRadioButton();
        jLLoteRacaoLeite1 = new javax.swing.JLabel();
        jTLoteRacaoLeite1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLLoteRacaoCorte1 = new javax.swing.JLabel();
        jTLoteVacinaCorte1 = new javax.swing.JTextField();
        jRVacinadeCorte1 = new javax.swing.JRadioButton();
        jTLoteRacaoCorte1 = new javax.swing.JTextField();
        jRRaçaoCorte1 = new javax.swing.JRadioButton();
        jTLoteVacinaLeite1 = new javax.swing.JTextField();
        jPEstoqueVacina = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLRelatorioEstoque = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jBGerar = new javax.swing.JButton();
        jRLote = new javax.swing.JRadioButton();
        jRTipo = new javax.swing.JRadioButton();
        jRPreço = new javax.swing.JRadioButton();
        jPEstoqueRaçao = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jRTipo2 = new javax.swing.JRadioButton();
        jBGerarRelatorio2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jRLote2 = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jRPreço2 = new javax.swing.JRadioButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximizable(true);
        setResizable(true);
        setTitle("Produtos");

        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jLLoteRaçaoCorte.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLLoteRaçaoCorte.setText("Lote Ração de Corte:");

        jLLoteVacinaLeite.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLLoteVacinaLeite.setText("Lote Vacina Leite :");

        jLPreçoRaçãoCorte.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLPreçoRaçãoCorte.setText("Preço Ração de Corte:");

        jLLoteRaçaoLeite.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLLoteRaçaoLeite.setText("Lote Ração Leite :");

        jLPreçoVacinaCorte.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLPreçoVacinaCorte.setText("Preço Vacina de Corte:");

        buttonGroup1.add(jRVacinadeCorte);
        jRVacinadeCorte.setSelected(true);
        jRVacinadeCorte.setText("Vacina de Corte");
        jRVacinadeCorte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRVacinadeCorteMouseClicked(evt);
            }
        });

        jLPreçoVacinaLeite.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLPreçoVacinaLeite.setText("Preço Vacina Leite :");

        jLLoteVacinaCorte.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLLoteVacinaCorte.setText("Lote Vacina de Corte :");

        buttonGroup1.add(jRVacinadeLeite);
        jRVacinadeLeite.setText("Vacina Leite");
        jRVacinadeLeite.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRVacinadeLeiteMouseClicked(evt);
            }
        });

        jCDia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        jQuantidade.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jQuantidade.setText("Quantidade:");

        jLPreçoRaçaoLeite.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLPreçoRaçaoLeite.setText("Preço Ração leite :");

        buttonGroup1.add(jRRaçaoLeite);
        jRRaçaoLeite.setText("Ração Leite");
        jRRaçaoLeite.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRRaçaoLeiteMouseClicked(evt);
            }
        });

        jCAno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030" }));

        jBAdicionar.setText("Adicionar Produto");
        jBAdicionar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBAdicionarMouseClicked(evt);
            }
        });

        buttonGroup1.add(jRRaçaodeCorte);
        jRRaçaodeCorte.setText("Ração de Corte");
        jRRaçaodeCorte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRRaçaodeCorteMouseClicked(evt);
            }
        });

        jCMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01- Janeiro", "02- Fevereiro", "03- Março", "04- Abril", "05- Maio", "06- Junho", "07- Julho", "08- Agosto", "09- Setembro", "10- Outubro", "11- Novembro", "12- Dezembro" }));

        jLData.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLData.setText("Data:");

        jLSeleçao.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLSeleçao.setText("Selecione o tipo do produto :");
        jLSeleçao.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(jLSeleçao)
                        .addGap(57, 57, 57)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRVacinadeCorte)
                            .addComponent(jRVacinadeLeite))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRRaçaoLeite)
                            .addComponent(jRRaçaodeCorte)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(380, 380, 380)
                        .addComponent(jBAdicionar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLLoteVacinaCorte)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTLoteVacinaCorte, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLLoteRaçaoCorte)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTLoteRaçaoCorte, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLPreçoVacinaCorte)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTPreçoVacinaCorte, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLPreçoRaçãoCorte)
                                            .addComponent(jQuantidade))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTPreçoRaçaoCorte, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(77, 77, 77)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLPreçoRaçaoLeite)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                    .addComponent(jLData)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jCDia, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(jLPreçoVacinaLeite))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLLoteRaçaoLeite, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLLoteVacinaLeite, javax.swing.GroupLayout.Alignment.TRAILING))))
                                .addGap(59, 59, 59)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTPreçoRaçaoLeite, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTLoteVacinaLeite, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTLoteRaçaoLeite, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTPreçoVacinaLeite, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jCMes, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCAno, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRVacinadeCorte)
                    .addComponent(jRRaçaodeCorte)
                    .addComponent(jLSeleçao))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRVacinadeLeite)
                    .addComponent(jRRaçaoLeite))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLLoteVacinaCorte)
                    .addComponent(jTLoteVacinaCorte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLLoteVacinaLeite)
                    .addComponent(jTLoteVacinaLeite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLLoteRaçaoCorte)
                    .addComponent(jTLoteRaçaoCorte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLLoteRaçaoLeite)
                    .addComponent(jTLoteRaçaoLeite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTPreçoVacinaCorte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLPreçoVacinaCorte)
                    .addComponent(jLPreçoVacinaLeite)
                    .addComponent(jTPreçoVacinaLeite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLPreçoRaçãoCorte)
                    .addComponent(jTPreçoRaçaoCorte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLPreçoRaçaoLeite)
                    .addComponent(jTPreçoRaçaoLeite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jQuantidade)
                    .addComponent(jTQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLData)
                    .addComponent(jCMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addComponent(jBAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(88, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(103, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Adicionar", jPanel5);

        buttonGroup4.add(jRRaçaoLeite1);
        jRRaçaoLeite1.setText("Ração Leite");
        jRRaçaoLeite1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRRaçaoLeite1MouseClicked(evt);
            }
        });

        jLLoteVacinaCorte1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLLoteVacinaCorte1.setText("Lote Vacina de Corte :");

        jLLoteVacinaLeite1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLLoteVacinaLeite1.setText("Lote Vacina Leite :");

        jBRemover.setText("Remover Produto");
        jBRemover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBRemoverMouseClicked(evt);
            }
        });

        buttonGroup4.add(jRVacinaLeite1);
        jRVacinaLeite1.setText("Vacina Leite");
        jRVacinaLeite1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRVacinaLeite1MouseClicked(evt);
            }
        });

        jLLoteRacaoLeite1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLLoteRacaoLeite1.setText("Lote Ração Leite :");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Selecione o tipo do produto :");

        jLLoteRacaoCorte1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLLoteRacaoCorte1.setText("Lote Ração de Corte :");

        buttonGroup4.add(jRVacinadeCorte1);
        jRVacinadeCorte1.setSelected(true);
        jRVacinadeCorte1.setText("Vacina de Corte");
        jRVacinadeCorte1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRVacinadeCorte1MouseClicked(evt);
            }
        });

        buttonGroup4.add(jRRaçaoCorte1);
        jRRaçaoCorte1.setText("Ração de Corte");
        jRRaçaoCorte1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRRaçaoCorte1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(jLabel9)
                        .addGap(67, 67, 67)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRVacinadeCorte1)
                            .addComponent(jRVacinaLeite1))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRRaçaoCorte1)
                            .addComponent(jRRaçaoLeite1)))
                    .addComponent(jLLoteRacaoCorte1)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTLoteVacinaLeite1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLLoteVacinaCorte1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTLoteVacinaCorte1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTLoteRacaoCorte1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(60, 60, 60)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLLoteVacinaLeite1)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLLoteRacaoLeite1)
                                    .addGap(46, 46, 46)
                                    .addComponent(jTLoteRacaoLeite1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(357, 357, 357)
                        .addComponent(jBRemover)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRVacinadeCorte1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jRRaçaoCorte1, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRVacinaLeite1)
                    .addComponent(jRRaçaoLeite1))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLLoteVacinaCorte1)
                            .addComponent(jTLoteVacinaCorte1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLLoteVacinaLeite1)
                            .addComponent(jTLoteVacinaLeite1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLLoteRacaoLeite1)
                            .addComponent(jTLoteRacaoLeite1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLLoteRacaoCorte1)
                            .addComponent(jTLoteRacaoCorte1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 152, Short.MAX_VALUE)
                .addComponent(jBRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(92, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(97, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(68, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Remover", jPanel6);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Lote", "Tipo", "Preço", "Quantidade"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jLRelatorioEstoque.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLRelatorioEstoque.setText("Relatório de Estoque :");

        jLabel1.setText("Ordenar por :");

        jBGerar.setText("Gerar Relatório Atualizado");
        jBGerar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBGerarMouseClicked(evt);
            }
        });

        buttonGroup5.add(jRLote);
        jRLote.setText("Lote");

        buttonGroup5.add(jRTipo);
        jRTipo.setSelected(true);
        jRTipo.setText("Tipo");

        buttonGroup5.add(jRPreço);
        jRPreço.setText("Preço");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(302, 302, 302)
                        .addComponent(jLRelatorioEstoque))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 826, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jBGerar, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                            .addGap(11, 11, 11)
                            .addComponent(jLabel1)
                            .addGap(72, 72, 72)
                            .addComponent(jRTipo)
                            .addGap(87, 87, 87)
                            .addComponent(jRLote)
                            .addGap(88, 88, 88)
                            .addComponent(jRPreço))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLRelatorioEstoque)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jRTipo)
                    .addComponent(jRLote)
                    .addComponent(jRPreço))
                .addGap(27, 27, 27)
                .addComponent(jBGerar, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPEstoqueVacinaLayout = new javax.swing.GroupLayout(jPEstoqueVacina);
        jPEstoqueVacina.setLayout(jPEstoqueVacinaLayout);
        jPEstoqueVacinaLayout.setHorizontalGroup(
            jPEstoqueVacinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPEstoqueVacinaLayout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );
        jPEstoqueVacinaLayout.setVerticalGroup(
            jPEstoqueVacinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPEstoqueVacinaLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Estoque Vacinas", jPEstoqueVacina);

        buttonGroup6.add(jRTipo2);
        jRTipo2.setSelected(true);
        jRTipo2.setText("Tipo");

        jBGerarRelatorio2.setText("Gerar Relatório Atualizado");
        jBGerarRelatorio2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBGerarRelatorio2MouseClicked(evt);
            }
        });

        jLabel2.setText("Ordenar por :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Relatório de Estoque :");

        buttonGroup6.add(jRLote2);
        jRLote2.setText("Lote");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Lote", "Tipo", "Preço", "Quantidade"
            }
        ));
        jScrollPane1.setViewportView(jTable2);

        buttonGroup6.add(jRPreço2);
        jRPreço2.setText("Preço");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                            .addGap(17, 17, 17)
                            .addComponent(jLabel2)
                            .addGap(65, 65, 65)
                            .addComponent(jRTipo2)
                            .addGap(74, 74, 74)
                            .addComponent(jRLote2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jRPreço2))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                            .addGap(269, 269, 269)
                            .addComponent(jBGerarRelatorio2, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 820, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(299, 299, 299)
                        .addComponent(jLabel3)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jRTipo2)
                    .addComponent(jRLote2)
                    .addComponent(jRPreço2))
                .addGap(29, 29, 29)
                .addComponent(jBGerarRelatorio2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPEstoqueRaçaoLayout = new javax.swing.GroupLayout(jPEstoqueRaçao);
        jPEstoqueRaçao.setLayout(jPEstoqueRaçaoLayout);
        jPEstoqueRaçaoLayout.setHorizontalGroup(
            jPEstoqueRaçaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPEstoqueRaçaoLayout.createSequentialGroup()
                .addContainerGap(72, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
        );
        jPEstoqueRaçaoLayout.setVerticalGroup(
            jPEstoqueRaçaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPEstoqueRaçaoLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Estoque Ração", jPEstoqueRaçao);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        
            if(jRVacinadeCorte.isSelected())
        {
            jTLoteRaçaoCorte.setEnabled(false);
            jTPreçoRaçaoCorte.setEnabled(false);
            jLLoteRaçaoCorte.setEnabled(false);
            jLPreçoRaçãoCorte.setEnabled(false);
            
            jTLoteRaçaoLeite.setEnabled(false);
            jTPreçoRaçaoLeite.setEnabled(false);
            jLLoteRaçaoLeite.setEnabled(false);
            jLPreçoRaçaoLeite.setEnabled(false);
            
            jLLoteVacinaLeite.setEnabled(false);
            jLPreçoVacinaLeite.setEnabled(false);
            jTPreçoVacinaLeite.setEnabled(false);
            jTLoteVacinaLeite.setEnabled(false);
            
            jTLoteVacinaCorte.setEnabled(true);
            jTPreçoVacinaCorte.setEnabled(true);
            jLLoteVacinaCorte.setEnabled(true);
            jLPreçoVacinaCorte.setEnabled(true);
            
        }
             if(jRVacinadeCorte1.isSelected())
        {
            jTLoteRacaoCorte1.setEnabled(false);
            jLLoteRacaoCorte1.setEnabled(false);
            
            jTLoteRacaoLeite1.setEnabled(false);
            jLLoteRacaoLeite1.setEnabled(false);
            
            jLLoteVacinaLeite1.setEnabled(false);
            jTLoteVacinaLeite1.setEnabled(false);
            
            jTLoteVacinaCorte1.setEnabled(true);
            jLLoteVacinaCorte1.setEnabled(true);
            
        }
        
        
    }//GEN-LAST:event_formWindowOpened

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        // TODO add your handling code here:
if(jTabbedPane1.getSelectedComponent().equals(jPEstoqueVacina))
        {
        
            try {
            Class.forName("org.postgresql.Driver");
            conn = DriverManager.getConnection(url, user, pws);
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        } catch (SQLException ex1) {
            JOptionPane.showMessageDialog(rootPane, ex1);
        }
            
            if(jRTipo.isSelected()){
                tabela = (DefaultTableModel) jTable1.getModel();
            tabela.setNumRows(0);
                cmd = "SELECT * from vacinas ORDER BY tipovacina";
                try {
                stm = conn.createStatement();
                returnquery = stm.executeQuery(cmd);
                while(returnquery.next()){
                    tabela.addRow(new Object[]{returnquery.getString("id"),returnquery.getString("lotevacina"),
                                returnquery.getString("tipovacina"),returnquery.getString("preçovacina"),returnquery.getString("quantidade")});
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(rootPane, ex);
            }
            }    
        }
     
if(jTabbedPane1.getSelectedComponent().equals(jPEstoqueRaçao))
        {
        
            try {
            Class.forName("org.postgresql.Driver");
            conn = DriverManager.getConnection(url, user, pws);
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        } catch (SQLException ex1) {
            JOptionPane.showMessageDialog(rootPane, ex1);
        }
            
            if(jRTipo2.isSelected()){
                tabela = (DefaultTableModel) jTable2.getModel();
            tabela.setNumRows(0);
                cmd = "SELECT * from raçao ORDER BY tiporaçao";
                try {
                stm = conn.createStatement();
                returnquery = stm.executeQuery(cmd);
                while(returnquery.next()){
                    tabela.addRow(new Object[]{returnquery.getString("id"),returnquery.getString("loteraçao"),
                                returnquery.getString("tiporaçao"),returnquery.getString("preçoraçao"),returnquery.getString("quantidade")});
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(rootPane, ex);
            }
            }    
        }

    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void jBGerarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBGerarMouseClicked
        // TODO add your handling code here:

        try {
            Class.forName("org.postgresql.Driver");
            conn = DriverManager.getConnection(url, user, pws);
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        } catch (SQLException ex1) {
            JOptionPane.showMessageDialog(rootPane, ex1);
        }
        tabela = (DefaultTableModel) jTable1.getModel();
        tabela.setNumRows(0);
        if(jRTipo.isSelected()){
            cmd = "SELECT * from vacinas ORDER BY tipovacina";
            try {
                stm = conn.createStatement();
                returnquery = stm.executeQuery(cmd);
                while(returnquery.next()){
                    tabela.addRow(new Object[]{returnquery.getString("id"),returnquery.getString("lotevacina"),
                        returnquery.getString("tipovacina"),returnquery.getString("preçovacina"),returnquery.getString("quantidade")});
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        }
        }
        if(jRLote.isSelected())
        {
            cmd = "SELECT * from vacinas ORDER BY lotevacina";
            try {
                stm = conn.createStatement();
                returnquery = stm.executeQuery(cmd);
                while(returnquery.next()){
                    tabela.addRow(new Object[]{returnquery.getString("id"),returnquery.getString("lotevacina"),
                        returnquery.getString("tipovacina"),returnquery.getString("preçovacina"),returnquery.getString("quantidade")});
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        }
        }
        if(jRPreço.isSelected()){
            cmd = "SELECT * from vacinas ORDER BY preçovacina";
            try {
                stm = conn.createStatement();
                returnquery = stm.executeQuery(cmd);
                while(returnquery.next()){
                    tabela.addRow(new Object[]{returnquery.getString("id"),returnquery.getString("lotevacina"),
                        returnquery.getString("tipovacina"),returnquery.getString("preçovacina"),returnquery.getString("quantidade")});
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        }
        }

    }//GEN-LAST:event_jBGerarMouseClicked

    private void jBRemoverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBRemoverMouseClicked
        // TODO add your handling code here:

        try {
            Class.forName("org.postgresql.Driver");
            conn = DriverManager.getConnection(url, user, pws);
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        } catch (SQLException ex1) {
            JOptionPane.showMessageDialog(rootPane, ex1);
        }

        if(jRVacinadeLeite.isSelected())
        {
            cmd = "DELETE FROM vacinas WHERE lotevacina =  " + jTLoteVacinaLeite1.getText();

            try {

                stm = conn.createStatement();
                stm.executeUpdate(cmd);
                JOptionPane.showMessageDialog(rootPane, "Registro deletado com sucesso");
                jTLoteVacinaLeite1.setText("");
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(rootPane, ex);
            }
        }

        if(jRVacinadeCorte.isSelected())
        {
            cmd = "DELETE FROM vacinas WHERE lotevacina =  " + jTLoteVacinaCorte1.getText();

            try {

                stm = conn.createStatement();
                stm.executeUpdate(cmd);
                JOptionPane.showMessageDialog(rootPane, "Registro deletado com sucesso");
                jTLoteVacinaCorte1.setText("");
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(rootPane, ex);
            }
        }

        if(jRRaçaodeCorte.isSelected())
        {
            cmd = "DELETE FROM raçao WHERE loteraçao =  " + jTLoteRacaoCorte1.getText();

            try {

                stm = conn.createStatement();
                stm.executeUpdate(cmd);
                JOptionPane.showMessageDialog(rootPane, "Registro deletado com sucesso");
                jTLoteRacaoCorte1.setText("");
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(rootPane, ex);
            }
        }

        if(jRRaçaoLeite1.isSelected())
        {
            cmd = "DELETE FROM raçao WHERE loteraçao =  " + jTLoteRacaoLeite1.getText();

            try {

                stm = conn.createStatement();
                stm.executeUpdate(cmd);
                JOptionPane.showMessageDialog(rootPane, "Registro deletado com sucesso");
                jTLoteRacaoLeite1.setText("");
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(rootPane, ex);
            }
        }

    }//GEN-LAST:event_jBRemoverMouseClicked

    private void jRRaçaoLeite1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRRaçaoLeite1MouseClicked
        // TODO add your handling code here:

        if(jRRaçaoLeite1.isSelected())
        {
            jTLoteRacaoCorte1.setEnabled(false);
            jLLoteRacaoCorte1.setEnabled(false);

            jTLoteRacaoLeite1.setEnabled(true);
            jLLoteRacaoLeite1.setEnabled(true);

            jLLoteVacinaLeite1.setEnabled(false);
            jTLoteVacinaLeite1.setEnabled(false);

            jTLoteVacinaCorte1.setEnabled(false);
            jLLoteVacinaCorte1.setEnabled(false);

        }
    }//GEN-LAST:event_jRRaçaoLeite1MouseClicked

    private void jRVacinaLeite1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRVacinaLeite1MouseClicked
        // TODO add your handling code here:

        if(jRVacinaLeite1.isSelected())
        {
            jTLoteRacaoCorte1.setEnabled(false);
            jLLoteRacaoCorte1.setEnabled(false);

            jTLoteRacaoLeite1.setEnabled(false);
            jLLoteRacaoLeite1.setEnabled(false);

            jLLoteVacinaLeite1.setEnabled(true);
            jTLoteVacinaLeite1.setEnabled(true);

            jTLoteVacinaCorte1.setEnabled(false);
            jLLoteVacinaCorte1.setEnabled(false);

        }

    }//GEN-LAST:event_jRVacinaLeite1MouseClicked

    private void jRRaçaoCorte1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRRaçaoCorte1MouseClicked
        // TODO add your handling code here:
        if(jRRaçaoCorte1.isSelected())
        {
            jTLoteRacaoCorte1.setEnabled(true);
            jLLoteRacaoCorte1.setEnabled(true);

            jTLoteRacaoLeite1.setEnabled(false);
            jLLoteRacaoLeite1.setEnabled(false);

            jLLoteVacinaLeite1.setEnabled(false);
            jTLoteVacinaLeite1.setEnabled(false);

            jTLoteVacinaCorte1.setEnabled(false);
            jLLoteVacinaCorte1.setEnabled(false);

        }

    }//GEN-LAST:event_jRRaçaoCorte1MouseClicked

    private void jRVacinadeCorte1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRVacinadeCorte1MouseClicked
        // TODO add your handling code here:
        if(jRVacinadeCorte1.isSelected())
        {
            jTLoteRacaoCorte1.setEnabled(false);
            jLLoteRacaoCorte1.setEnabled(false);

            jTLoteRacaoLeite1.setEnabled(false);
            jLLoteRacaoLeite1.setEnabled(false);

            jLLoteVacinaLeite1.setEnabled(false);
            jTLoteVacinaLeite1.setEnabled(false);

            jTLoteVacinaCorte1.setEnabled(true);
            jLLoteVacinaCorte1.setEnabled(true);

        }

    }//GEN-LAST:event_jRVacinadeCorte1MouseClicked

    private void jRRaçaoLeiteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRRaçaoLeiteMouseClicked
        // TODO add your handling code here:
        if(jRRaçaoLeite.isSelected())
        {
            jTLoteRaçaoCorte.setEnabled(false);
            jTPreçoRaçaoCorte.setEnabled(false);
            jLLoteRaçaoCorte.setEnabled(false);
            jLPreçoRaçãoCorte.setEnabled(false);

            jTLoteRaçaoLeite.setEnabled(true);
            jTPreçoRaçaoLeite.setEnabled(true);
            jLLoteRaçaoLeite.setEnabled(true);
            jLPreçoRaçaoLeite.setEnabled(true);

            jLLoteVacinaLeite.setEnabled(false);
            jLPreçoVacinaLeite.setEnabled(false);
            jTPreçoVacinaLeite.setEnabled(false);
            jTLoteVacinaLeite.setEnabled(false);

            jTLoteVacinaCorte.setEnabled(false);
            jTPreçoVacinaCorte.setEnabled(false);
            jLLoteVacinaCorte.setEnabled(false);
            jLPreçoVacinaCorte.setEnabled(false);

        }

    }//GEN-LAST:event_jRRaçaoLeiteMouseClicked

    private void jRVacinadeLeiteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRVacinadeLeiteMouseClicked
        // TODO add your handling code here:
        if(jRVacinadeLeite.isSelected())
        {
            jTLoteRaçaoCorte.setEnabled(false);
            jTPreçoRaçaoCorte.setEnabled(false);
            jLLoteRaçaoCorte.setEnabled(false);
            jLPreçoRaçãoCorte.setEnabled(false);

            jTLoteRaçaoLeite.setEnabled(false);
            jTPreçoRaçaoLeite.setEnabled(false);
            jLLoteRaçaoLeite.setEnabled(false);
            jLPreçoRaçaoLeite.setEnabled(false);

            jLLoteVacinaLeite.setEnabled(true);
            jLPreçoVacinaLeite.setEnabled(true);
            jTPreçoVacinaLeite.setEnabled(true);
            jTLoteVacinaLeite.setEnabled(true);

            jTLoteVacinaCorte.setEnabled(false);
            jTPreçoVacinaCorte.setEnabled(false);
            jLLoteVacinaCorte.setEnabled(false);
            jLPreçoVacinaCorte.setEnabled(false);

        }

    }//GEN-LAST:event_jRVacinadeLeiteMouseClicked

    private void jBAdicionarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBAdicionarMouseClicked
        // TODO add your handling code here:
        
        try {
            Class.forName("org.postgresql.Driver");
            conn = DriverManager.getConnection(url, user, pws);
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        } catch (SQLException ex1) {
            JOptionPane.showMessageDialog(rootPane, ex1);
        }
        if(jRVacinadeCorte.isSelected())
        {
            float saldo = 0;
            cmd = "INSERT INTO vacinas(lotevacina,tipovacina,preçovacina,quantidade) "
            + "VALUES('"+jTLoteVacinaCorte.getText()+"',"
            + "' Vacina de Corte ',"+Float.parseFloat(jTPreçoVacinaCorte.getText())+ ","+Integer.parseInt(jTQuantidade.getText())+")";
            try {

                stm = conn.createStatement();
                stm.executeUpdate(cmd);
                String temp, list[];
                temp = jCMes.getSelectedItem().toString();
                list = temp.split("-");
                String data = jCAno.getSelectedItem().toString() + "-" + list[0] + "-" + jCDia.getSelectedItem().toString();
                cmd = "SELECT * from financas ORDER BY transacao";
                returnquery = stm.executeQuery(cmd);
                while(returnquery.next()){
                    if(returnquery.getString("tipotransacao").equals("( + )"))
                        saldo = saldo + Float.parseFloat(returnquery.getString("valor"));
                    else
                        saldo = saldo - Float.parseFloat(returnquery.getString("valor"));
                }
                cmd = "INSERT INTO financas(datatransacao, valor, tipotransacao, saldoatual) VALUES('" + data + "'," + Float.parseFloat(jTPreçoVacinaCorte.getText()) 
                        + ",'( - )'," + (saldo - Float.parseFloat(jTPreçoVacinaCorte.getText())) + ")";
                stm.executeUpdate(cmd);
                JOptionPane.showMessageDialog(rootPane, "Registro inserido com sucesso");
                jTLoteVacinaCorte.setText("");
                jTPreçoVacinaCorte.setText("");
                jTQuantidade.setText("");
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(rootPane, ex);
            }
        }

        if(jRVacinadeLeite.isSelected())
        {
            float saldo = 0;
            cmd = "INSERT INTO vacinas(lotevacina,tipovacina,preçovacina,quantidade) "
            + "VALUES('"+jTLoteVacinaLeite.getText()+"',"
            + "' Vacina Leite ',"+Float.parseFloat(jTPreçoVacinaLeite.getText())+ ","+Integer.parseInt(jTQuantidade.getText())+")";
            try {

                stm = conn.createStatement();
                stm.executeUpdate(cmd);
                String temp, list[];
                temp = jCMes.getSelectedItem().toString();
                list = temp.split("-");
                String data = jCAno.getSelectedItem().toString() + "-" + list[0] + "-" + jCDia.getSelectedItem().toString();
                cmd = "SELECT * from financas ORDER BY transacao";
                returnquery = stm.executeQuery(cmd);
                while(returnquery.next())
                    if(returnquery.getString("tipotransacao").equals("( + )"))
                        saldo = saldo + Float.parseFloat(returnquery.getString("valor"));
                    else
                        saldo = saldo - Float.parseFloat(returnquery.getString("valor"));
                cmd = "INSERT INTO financas(datatransacao, valor, tipotransacao, saldoatual) VALUES('" + data + "'," + Float.parseFloat(jTPreçoVacinaLeite.getText()) 
                        + ",'( - )'," + (saldo - Float.parseFloat(jTPreçoVacinaLeite.getText())) + ")";
                stm.executeUpdate(cmd);
                JOptionPane.showMessageDialog(rootPane, "Registro inserido com sucesso");
                jTLoteVacinaLeite.setText("");
                jTPreçoVacinaLeite.setText("");
                jTQuantidade.setText("");
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(rootPane, ex);
            }
        }
        if(jRRaçaodeCorte.isSelected())
        {
            float saldo = 0;
            cmd = "INSERT INTO raçao(loteraçao,tiporaçao,preçoraçao,quantidade) "
            + "VALUES('"+jTLoteRaçaoCorte.getText()+"',"
            + "' Ração de Corte ',"+Float.parseFloat(jTPreçoRaçaoCorte.getText())+ ","+Integer.parseInt(jTQuantidade.getText())+")";
            try {

                stm = conn.createStatement();
                stm.executeUpdate(cmd);
                String temp, list[];
                temp = jCMes.getSelectedItem().toString();
                list = temp.split("-");
                String data = jCAno.getSelectedItem().toString() + "-" + list[0] + "-" + jCDia.getSelectedItem().toString();
                cmd = "SELECT * from financas ORDER BY transacao";
                returnquery = stm.executeQuery(cmd);
                while(returnquery.next())
                    if(returnquery.getString("tipotransacao").equals("( + )"))
                        saldo = saldo + Float.parseFloat(returnquery.getString("valor"));
                    else
                        saldo = saldo - Float.parseFloat(returnquery.getString("valor"));
                cmd = "INSERT INTO financas(datatransacao, valor, tipotransacao, saldoatual) VALUES('" + data + "'," + Float.parseFloat(jTPreçoRaçaoCorte.getText())
                        + ",'( - )'," + (saldo - Float.parseFloat(jTPreçoRaçaoCorte.getText())) + ")";
                stm.executeUpdate(cmd);
                JOptionPane.showMessageDialog(rootPane, "Registro inserido com sucesso");
                jTLoteRaçaoCorte.setText("");
                jTPreçoRaçaoCorte.setText("");
                jTQuantidade.setText("");
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(rootPane, ex);
            }
        }

        if(jRRaçaoLeite.isSelected())
        {
            float saldo = 0;
            cmd = "INSERT INTO raçao(loteraçao,tiporaçao,preçoraçao,quantidade) "
            + "VALUES('"+jTLoteRaçaoLeite.getText()+"',"
            + "' Ração Leite ',"+Float.parseFloat(jTPreçoRaçaoLeite.getText())+ ","+Integer.parseInt(jTQuantidade.getText())+")";
            try {

                stm = conn.createStatement();
                stm.executeUpdate(cmd);
                String temp, list[];
                temp = jCMes.getSelectedItem().toString();
                list = temp.split("-");
                String data = jCAno.getSelectedItem().toString() + "-" + list[0] + "-" + jCDia.getSelectedItem().toString();
                cmd = "SELECT * from financas ORDER BY transacao";
                returnquery = stm.executeQuery(cmd);
                while(returnquery.next())
                    if(returnquery.getString("tipotransacao").equals("( + )"))
                        saldo = saldo + Float.parseFloat(returnquery.getString("valor"));
                    else
                        saldo = saldo - Float.parseFloat(returnquery.getString("valor"));
                cmd = "INSERT INTO financas(datatransacao, valor, tipotransacao, saldoatual) VALUES('" + data + "'," + Float.parseFloat(jTPreçoRaçaoLeite.getText()) 
                        + ",'( - )'," + (saldo - Float.parseFloat(jTPreçoRaçaoLeite.getText())) + ")";
                stm.executeUpdate(cmd);
                JOptionPane.showMessageDialog(rootPane, "Registro inserido com sucesso");
                jTLoteRaçaoLeite.setText("");
                jTPreçoRaçaoLeite.setText("");
                jTQuantidade.setText("");
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(rootPane, ex);
            }
        }

    }//GEN-LAST:event_jBAdicionarMouseClicked

    private void jRRaçaodeCorteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRRaçaodeCorteMouseClicked
        // TODO add your handling code here:

        if(jRRaçaodeCorte.isSelected())
        {
            jTLoteRaçaoCorte.setEnabled(true);
            jTPreçoRaçaoCorte.setEnabled(true);
            jLLoteRaçaoCorte.setEnabled(true);
            jLPreçoRaçãoCorte.setEnabled(true);

            jTLoteRaçaoLeite.setEnabled(false);
            jTPreçoRaçaoLeite.setEnabled(false);
            jLLoteRaçaoLeite.setEnabled(false);
            jLPreçoRaçaoLeite.setEnabled(false);

            jLLoteVacinaLeite.setEnabled(false);
            jLPreçoVacinaLeite.setEnabled(false);
            jTPreçoVacinaLeite.setEnabled(false);
            jTLoteVacinaLeite.setEnabled(false);

            jTLoteVacinaCorte.setEnabled(false);
            jTPreçoVacinaCorte.setEnabled(false);
            jLLoteVacinaCorte.setEnabled(false);
            jLPreçoVacinaCorte.setEnabled(false);

        }

    }//GEN-LAST:event_jRRaçaodeCorteMouseClicked

    private void jRVacinadeCorteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRVacinadeCorteMouseClicked
        // TODO add your handling code here:
        if(jRVacinadeCorte.isSelected())
        {
            jTLoteRaçaoCorte.setEnabled(false);
            jTPreçoRaçaoCorte.setEnabled(false);
            jLLoteRaçaoCorte.setEnabled(false);
            jLPreçoRaçãoCorte.setEnabled(false);

            jTLoteRaçaoLeite.setEnabled(false);
            jTPreçoRaçaoLeite.setEnabled(false);
            jLLoteRaçaoLeite.setEnabled(false);
            jLPreçoRaçaoLeite.setEnabled(false);

            jLLoteVacinaLeite.setEnabled(false);
            jLPreçoVacinaLeite.setEnabled(false);
            jTPreçoVacinaLeite.setEnabled(false);
            jTLoteVacinaLeite.setEnabled(false);

            jTLoteVacinaCorte.setEnabled(true);
            jTPreçoVacinaCorte.setEnabled(true);
            jLLoteVacinaCorte.setEnabled(true);
            jLPreçoVacinaCorte.setEnabled(true);

        }
    }//GEN-LAST:event_jRVacinadeCorteMouseClicked

    private void jBGerarRelatorio2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBGerarRelatorio2MouseClicked
        // TODO add your handling code here:
        
         try {
            Class.forName("org.postgresql.Driver");
            conn = DriverManager.getConnection(url, user, pws);
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        } catch (SQLException ex1) {
            JOptionPane.showMessageDialog(rootPane, ex1);
        }
        tabela = (DefaultTableModel) jTable2.getModel();
        tabela.setNumRows(0);
        if(jRTipo2.isSelected()){
                cmd = "SELECT * from raçao ORDER BY tiporaçao";
                try {
                stm = conn.createStatement();
                returnquery = stm.executeQuery(cmd);
                while(returnquery.next()){
                    tabela.addRow(new Object[]{returnquery.getString("id"),returnquery.getString("loteraçao"),
                                returnquery.getString("tiporaçao"),returnquery.getString("preçoraçao"),returnquery.getString("quantidade")});
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(rootPane, ex);
            }
            }
        if(jRLote2.isSelected())
            {
                cmd = "SELECT * from raçao ORDER BY loteraçao";
                try {
                stm = conn.createStatement();
                returnquery = stm.executeQuery(cmd);
                while(returnquery.next()){
                    tabela.addRow(new Object[]{returnquery.getString("id"),returnquery.getString("loteraçao"),
                                returnquery.getString("tiporaçao"),returnquery.getString("preçoraçao"),returnquery.getString("quantidade")});
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(rootPane, ex);
            }
            }
        if(jRPreço2.isSelected()){
                cmd = "SELECT * from raçao ORDER BY preçoraçao";
                try {
                stm = conn.createStatement();
                returnquery = stm.executeQuery(cmd);
                while(returnquery.next()){
                    tabela.addRow(new Object[]{returnquery.getString("id"),returnquery.getString("loteraçao"),
                                returnquery.getString("tiporaçao"),returnquery.getString("preçoraçao"),returnquery.getString("quantidade")});
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(rootPane, ex);
            }
            }
        
        
    }//GEN-LAST:event_jBGerarRelatorio2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EstoqueGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EstoqueGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EstoqueGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EstoqueGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EstoqueGUI().setVisible(true);
            }
        });
    }
    private String cmd;
    private String pws = "jpcn2503";
    private String user = "postgres";
    private String url = "jdbc:postgresql://localhost:5433/ProjetoFinal";
    private ResultSet returnquery; 
    private Connection conn; 
    private Statement stm; 
    private DefaultTableModel tabela;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.JButton jBAdicionar;
    private javax.swing.JButton jBGerar;
    private javax.swing.JButton jBGerarRelatorio2;
    private javax.swing.JButton jBRemover;
    private javax.swing.JComboBox<String> jCAno;
    private javax.swing.JComboBox<String> jCDia;
    private javax.swing.JComboBox<String> jCMes;
    private javax.swing.JLabel jLData;
    private javax.swing.JLabel jLLoteRacaoCorte1;
    private javax.swing.JLabel jLLoteRacaoLeite1;
    private javax.swing.JLabel jLLoteRaçaoCorte;
    private javax.swing.JLabel jLLoteRaçaoLeite;
    private javax.swing.JLabel jLLoteVacinaCorte;
    private javax.swing.JLabel jLLoteVacinaCorte1;
    private javax.swing.JLabel jLLoteVacinaLeite;
    private javax.swing.JLabel jLLoteVacinaLeite1;
    private javax.swing.JLabel jLPreçoRaçaoLeite;
    private javax.swing.JLabel jLPreçoRaçãoCorte;
    private javax.swing.JLabel jLPreçoVacinaCorte;
    private javax.swing.JLabel jLPreçoVacinaLeite;
    private javax.swing.JLabel jLRelatorioEstoque;
    private javax.swing.JLabel jLSeleçao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPEstoqueRaçao;
    private javax.swing.JPanel jPEstoqueVacina;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel jQuantidade;
    private javax.swing.JRadioButton jRLote;
    private javax.swing.JRadioButton jRLote2;
    private javax.swing.JRadioButton jRPreço;
    private javax.swing.JRadioButton jRPreço2;
    private javax.swing.JRadioButton jRRaçaoCorte1;
    private javax.swing.JRadioButton jRRaçaoLeite;
    private javax.swing.JRadioButton jRRaçaoLeite1;
    private javax.swing.JRadioButton jRRaçaodeCorte;
    private javax.swing.JRadioButton jRTipo;
    private javax.swing.JRadioButton jRTipo2;
    private javax.swing.JRadioButton jRVacinaLeite1;
    private javax.swing.JRadioButton jRVacinadeCorte;
    private javax.swing.JRadioButton jRVacinadeCorte1;
    private javax.swing.JRadioButton jRVacinadeLeite;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTLoteRacaoCorte1;
    private javax.swing.JTextField jTLoteRacaoLeite1;
    private javax.swing.JTextField jTLoteRaçaoCorte;
    private javax.swing.JTextField jTLoteRaçaoLeite;
    private javax.swing.JTextField jTLoteVacinaCorte;
    private javax.swing.JTextField jTLoteVacinaCorte1;
    private javax.swing.JTextField jTLoteVacinaLeite;
    private javax.swing.JTextField jTLoteVacinaLeite1;
    private javax.swing.JTextField jTPreçoRaçaoCorte;
    private javax.swing.JTextField jTPreçoRaçaoLeite;
    private javax.swing.JTextField jTPreçoVacinaCorte;
    private javax.swing.JTextField jTPreçoVacinaLeite;
    private javax.swing.JTextField jTQuantidade;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
