/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIs;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author joaopcandido
 */
public class FinancasGUI extends javax.swing.JInternalFrame {

    /**
     * Creates new form FinancasGUI
     */
    public FinancasGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableFinancas = new javax.swing.JTable();
        jLFiltrarData1 = new javax.swing.JLabel();
        jCFiltrarAno2 = new javax.swing.JComboBox<>();
        jCFiltrarDia2 = new javax.swing.JComboBox<>();
        jCFiltrarMes2 = new javax.swing.JComboBox<>();
        jCFiltrarMes1 = new javax.swing.JComboBox<>();
        jCFiltrarAno1 = new javax.swing.JComboBox<>();
        jLFiltrarData2 = new javax.swing.JLabel();
        jCFiltrarDia1 = new javax.swing.JComboBox<>();
        jBFiltrarData = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jTableFinancas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Transação", "Data (AAAA-MM-DD)", "Valor", "Tipo (Crédito - Débito)", "Saldo"
            }
        ));
        jScrollPane1.setViewportView(jTableFinancas);

        jLFiltrarData1.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLFiltrarData1.setText("De:");

        jCFiltrarAno2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ano", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030" }));

        jCFiltrarDia2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dia", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        jCFiltrarMes2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mes", "01- Janeiro", "02- Fevereiro", "03- Março", "04- Abril", "05- Maio", "06- Junho", "07- Julho", "08- Agosto", "09- Setembro", "10- Outubro", "11- Novembro", "12- Dezembro" }));

        jCFiltrarMes1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mes", "01- Janeiro", "02- Fevereiro", "03- Março", "04- Abril", "05- Maio", "06- Junho", "07- Julho", "08- Agosto", "09- Setembro", "10- Outubro", "11- Novembro", "12- Dezembro" }));

        jCFiltrarAno1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ano", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030" }));

        jLFiltrarData2.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLFiltrarData2.setText("Até:");

        jCFiltrarDia1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dia", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        jBFiltrarData.setText("Filtrar Data");
        jBFiltrarData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBFiltrarDataMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1281, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(263, 263, 263)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLFiltrarData1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCFiltrarDia1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCFiltrarMes1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCFiltrarAno1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLFiltrarData2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCFiltrarDia2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCFiltrarMes2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCFiltrarAno2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(267, 267, 267)
                .addComponent(jBFiltrarData, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCFiltrarDia1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCFiltrarMes1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCFiltrarAno1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLFiltrarData1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLFiltrarData2)
                            .addComponent(jCFiltrarDia2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCFiltrarMes2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCFiltrarAno2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jBFiltrarData, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        try {
            Class.forName("org.postgresql.Driver");
            conn = DriverManager.getConnection(url, user, pws);
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        } catch (SQLException ex1) {
            JOptionPane.showMessageDialog(rootPane, ex1);
        }
        tabela = (DefaultTableModel) jTableFinancas.getModel();
        tabela.setNumRows(0);
        cmd = "SELECT * from financas ORDER BY transacao";
        try {
            stm = conn.createStatement();
            returnquery = stm.executeQuery(cmd);
            while(returnquery.next()){
                tabela.addRow(new Object[]{returnquery.getString("transacao"),returnquery.getString("datatransacao"),
                            returnquery.getString("valor"),returnquery.getString("tipotransacao"),returnquery.getString("saldoatual")});
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        }
        try {
            conn.close();
        } catch (SQLException ex) {
            Logger.getLogger(VendasBD.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formInternalFrameOpened

    private void jBFiltrarDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBFiltrarDataMouseClicked
        // TODO add your handling code here:
        try {
            Class.forName("org.postgresql.Driver");
            conn = DriverManager.getConnection(url, user, pws);
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        } catch (SQLException ex1) {
            JOptionPane.showMessageDialog(rootPane, ex1);
        }
        tabela = (DefaultTableModel) jTableFinancas.getModel();
        tabela.setNumRows(0);
        String temp1, temp2, list1[], list2[];
        temp1 = jCFiltrarMes1.getSelectedItem().toString();
        list1 = temp1.split("-");
        String data1 = jCFiltrarAno1.getSelectedItem().toString() + "-" + list1[0] + "-" + jCFiltrarDia1.getSelectedItem().toString();
        temp2 = jCFiltrarMes2.getSelectedItem().toString();
        list2 = temp1.split("-");
        String data2 = jCFiltrarAno2.getSelectedItem().toString() + "-" + list2[0] + "-" + jCFiltrarDia2.getSelectedItem().toString();
        if (!data1.equals("Ano-Mes-Dia") && data2.equals("Ano-Mes-Dia")){
            cmd = "SELECT * from financas where datatransaco >= '" + data1 + "' ORDER BY datatransacao";
            try {
                stm = conn.createStatement();
                registroPorData = (stm.executeQuery(cmd));  
                while(registroPorData.next()){
                    tabela.addRow(new Object[]{registroPorData.getString("transacao"),registroPorData.getString("datatransacao"),
                            registroPorData.getString("valor"),registroPorData.getString("tipotransacao"),registroPorData.getString("saldoatual")});
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
        }
        else if (data1.equals("Ano-Mes-Dia") && !data2.equals("Ano-Mes-Dia")){
            cmd = "SELECT * from financas where datatransacao <= '" + data2 + "' ORDER BY datatransacao";
            try {
                stm = conn.createStatement();
                registroPorData = (stm.executeQuery(cmd)); 
                while(registroPorData.next()){
                    tabela.addRow(new Object[]{registroPorData.getString("transacao"),registroPorData.getString("datatransacao"),
                            registroPorData.getString("valor"),registroPorData.getString("tipotransacao"),registroPorData.getString("saldoatual")});
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
        }
        else{
            cmd = "SELECT * from financas where datatransacao between '" + data1 + "' and '" + data2 + "' ORDER BY datatransacao";
            try {
                stm = conn.createStatement();
                registroPorData = (stm.executeQuery(cmd)); 
                while(registroPorData.next()){
                    tabela.addRow(new Object[]{registroPorData.getString("transacao"),registroPorData.getString("datatransacao"),
                            registroPorData.getString("valor"),registroPorData.getString("tipotransacao"),registroPorData.getString("saldoatual")});
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
        }
        try {
            conn.close();
        } catch (SQLException ex) {
            Logger.getLogger(VendasBD.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBFiltrarDataMouseClicked

    
    private String cmd;
    private String pws = "jpcn2503";
    private String user = "postgres";
    private String url = "jdbc:postgresql://localhost:5433/ProjetoFinal";
    private ResultSet returnquery;
    private ResultSet registroPorData;
    private Connection conn; 
    private Statement stm; 
    private DefaultTableModel tabela;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBFiltrarData;
    private javax.swing.JComboBox<String> jCFiltrarAno1;
    private javax.swing.JComboBox<String> jCFiltrarAno2;
    private javax.swing.JComboBox<String> jCFiltrarDia1;
    private javax.swing.JComboBox<String> jCFiltrarDia2;
    private javax.swing.JComboBox<String> jCFiltrarMes1;
    private javax.swing.JComboBox<String> jCFiltrarMes2;
    private javax.swing.JLabel jLFiltrarData1;
    private javax.swing.JLabel jLFiltrarData2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableFinancas;
    // End of variables declaration//GEN-END:variables
}
