package GUIs;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.util.converter.IntegerStringConverter;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author victor
 */
public class GadosGUI extends javax.swing.JInternalFrame {

    /**
     * Creates new form GUI
     */
    public GadosGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPCadastro = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jBCadastrar = new javax.swing.JButton();
        jLDataCadastro = new javax.swing.JLabel();
        jCBDiaCadastro = new javax.swing.JComboBox<>();
        jCBMesCadastro = new javax.swing.JComboBox<>();
        jCBAnoCadastro = new javax.swing.JComboBox<>();
        jLTipo = new javax.swing.JLabel();
        jRGadoDeCorteCadastro = new javax.swing.JRadioButton();
        jRGadoDeLeiteCadastro = new javax.swing.JRadioButton();
        jLCodigoDeIdentificacaoCadastro = new javax.swing.JLabel();
        jLPesoCadastro = new javax.swing.JLabel();
        jTCodigoDeIdentificacaoCadastro = new javax.swing.JTextField();
        jTPesoCadastro = new javax.swing.JTextField();
        jPAtualizar = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jCBCodIdenAtualizar = new javax.swing.JComboBox<>();
        jRPeso = new javax.swing.JRadioButton();
        jBAtualizar = new javax.swing.JButton();
        jTAtualizar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabelaAtualizar = new javax.swing.JTable();
        jLAtualizar = new javax.swing.JLabel();
        jRStatus = new javax.swing.JRadioButton();
        jTCodIdentAtualizar = new javax.swing.JTextField();
        jLSelecaoCodIdenCBAtualizar = new javax.swing.JLabel();
        jLAviso1 = new javax.swing.JLabel();
        jLCodigoDeIdentificacaoAtualizar = new javax.swing.JLabel();
        jLOu = new javax.swing.JLabel();
        jBPesquisar = new javax.swing.JButton();
        jPVisualizar = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jRStatusVisualizar = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jCBMesInicial = new javax.swing.JComboBox<>();
        jCBMesFinal = new javax.swing.JComboBox<>();
        jRCodigoVisualizar = new javax.swing.JRadioButton();
        jLDataInicial = new javax.swing.JLabel();
        jCBAnoInicial = new javax.swing.JComboBox<>();
        jCBDiaInicial = new javax.swing.JComboBox<>();
        jCBAnoFinal = new javax.swing.JComboBox<>();
        jBVisualizar = new javax.swing.JButton();
        jRTipoVisualizar = new javax.swing.JRadioButton();
        jLDataFianl = new javax.swing.JLabel();
        jRDataVisualizar = new javax.swing.JRadioButton();
        jCBDiaFinal = new javax.swing.JComboBox<>();
        jRPesoVisualizar = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTabelaVisualizar = new javax.swing.JTable();

        jLabel1.setText("jLabel1");

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximizable(true);
        setResizable(true);
        setTitle("Gados");

        jTabbedPane2.setToolTipText("");
        jTabbedPane2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane2MouseClicked(evt);
            }
        });

        jBCadastrar.setText("Cadastrar");
        jBCadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBCadastrarMouseClicked(evt);
            }
        });

        jLDataCadastro.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLDataCadastro.setText("Data:");

        jCBDiaCadastro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        jCBMesCadastro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01- Janeiro", "02- Fevereiro", "03- Março", "04- Abril", "05- Maio", "06- Junho", "07- Julho", "08- Agosto", "09- Setembro", "10- Outubro", "11- Novembro", "12- Dezembro", " " }));

        jCBAnoCadastro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032", "2033", "2034", "2035", "2036", "2037", "2038", "2039", "2040" }));

        jLTipo.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLTipo.setText("Selecione o tipo do Gado:");

        buttonGroup1.add(jRGadoDeCorteCadastro);
        jRGadoDeCorteCadastro.setSelected(true);
        jRGadoDeCorteCadastro.setText("Gado de Corte");

        buttonGroup1.add(jRGadoDeLeiteCadastro);
        jRGadoDeLeiteCadastro.setText("Gado de Leite");

        jLCodigoDeIdentificacaoCadastro.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLCodigoDeIdentificacaoCadastro.setText("Código de Identificação:");

        jLPesoCadastro.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLPesoCadastro.setText("Peso:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLTipo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jRGadoDeCorteCadastro)
                        .addGap(45, 45, 45)
                        .addComponent(jRGadoDeLeiteCadastro)
                        .addGap(4, 4, 4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLCodigoDeIdentificacaoCadastro)
                            .addComponent(jLPesoCadastro)
                            .addComponent(jLDataCadastro))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jBCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jCBDiaCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCBMesCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCBAnoCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTPesoCadastro)
                            .addComponent(jTCodigoDeIdentificacaoCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(43, 43, 43))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRGadoDeCorteCadastro)
                    .addComponent(jRGadoDeLeiteCadastro))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLCodigoDeIdentificacaoCadastro)
                    .addComponent(jTCodigoDeIdentificacaoCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLPesoCadastro)
                    .addComponent(jTPesoCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLDataCadastro)
                    .addComponent(jCBDiaCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCBAnoCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCBMesCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jBCadastrar)
                .addGap(0, 18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPCadastroLayout = new javax.swing.GroupLayout(jPCadastro);
        jPCadastro.setLayout(jPCadastroLayout);
        jPCadastroLayout.setHorizontalGroup(
            jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPCadastroLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(29, 29, 29))
        );
        jPCadastroLayout.setVerticalGroup(
            jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCadastroLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(283, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Cadastro", jPCadastro);

        jCBCodIdenAtualizar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione um código existente", " " }));

        buttonGroup3.add(jRPeso);
        jRPeso.setSelected(true);
        jRPeso.setText("Peso");

        jBAtualizar.setText("Atualizar");
        jBAtualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBAtualizarMouseClicked(evt);
            }
        });

        jTabelaAtualizar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Código", "Tipo", "Peso", "Status"
            }
        ));
        jScrollPane1.setViewportView(jTabelaAtualizar);

        jLAtualizar.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLAtualizar.setText("Atualizar:");

        buttonGroup3.add(jRStatus);
        jRStatus.setText("Status");

        jLSelecaoCodIdenCBAtualizar.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLSelecaoCodIdenCBAtualizar.setText("Selecione o Código de Identificação:");

        jLAviso1.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLAviso1.setForeground(new java.awt.Color(246, 9, 9));

        jLCodigoDeIdentificacaoAtualizar.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLCodigoDeIdentificacaoAtualizar.setText("Digite o Código de Identificação:");

        jLOu.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLOu.setText("Ou");

        jBPesquisar.setText("Pesquisar");
        jBPesquisar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBPesquisarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addComponent(jLOu))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(230, 230, 230)
                                .addComponent(jBPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLAviso1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLSelecaoCodIdenCBAtualizar)
                            .addComponent(jLCodigoDeIdentificacaoAtualizar))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCBCodIdenAtualizar, 0, 277, Short.MAX_VALUE)
                            .addComponent(jTCodIdentAtualizar)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLAtualizar)
                        .addGap(18, 18, 18)
                        .addComponent(jRPeso)
                        .addGap(18, 18, 18)
                        .addComponent(jRStatus)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jBAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jTAtualizar))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLSelecaoCodIdenCBAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCBCodIdenAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLOu)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLCodigoDeIdentificacaoAtualizar)
                    .addComponent(jTCodIdentAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jBPesquisar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLAviso1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLAtualizar)
                    .addComponent(jRPeso)
                    .addComponent(jRStatus)
                    .addComponent(jTAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(jBAtualizar)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPAtualizarLayout = new javax.swing.GroupLayout(jPAtualizar);
        jPAtualizar.setLayout(jPAtualizarLayout);
        jPAtualizarLayout.setHorizontalGroup(
            jPAtualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPAtualizarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPAtualizarLayout.setVerticalGroup(
            jPAtualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPAtualizarLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Atualizar", jPAtualizar);

        buttonGroup4.add(jRStatusVisualizar);
        jRStatusVisualizar.setText("Status");
        jRStatusVisualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRStatusVisualizarMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabel2.setText("Ordenar por:");

        jCBMesInicial.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mes", "01- Janeiro", "02- Fevereiro", "03- Março", "04- Abril", "05- Maio", "06- Junho", "07- Julho", "08- Agosto", "09- Setembro", "10- Outubro", "11- Novembro", "12- Dezembro" }));

        jCBMesFinal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mes", "01- Janeiro", "02- Fevereiro", "03- Março", "04- Abril", "05- Maio", "06- Junho", "07- Julho", "08- Agosto", "09- Setembro", "10- Outubro", "11- Novembro", "12- Dezembro" }));

        buttonGroup4.add(jRCodigoVisualizar);
        jRCodigoVisualizar.setSelected(true);
        jRCodigoVisualizar.setText("Código");
        jRCodigoVisualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRCodigoVisualizarMouseClicked(evt);
            }
        });

        jLDataInicial.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLDataInicial.setText("Data inicial:");

        jCBAnoInicial.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ano", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032", "2033", "2034", "2035", "2036", "2037", "2038", "2039", "2040" }));

        jCBDiaInicial.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dia", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        jCBAnoFinal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ano", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032", "2033", "2034", "2035", "2036", "2037", "2038", "2039", "2040" }));

        jBVisualizar.setText("Visualizar");
        jBVisualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBVisualizarMouseClicked(evt);
            }
        });

        buttonGroup4.add(jRTipoVisualizar);
        jRTipoVisualizar.setText("Tipo");
        jRTipoVisualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRTipoVisualizarMouseClicked(evt);
            }
        });

        jLDataFianl.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLDataFianl.setText("Data final:");

        buttonGroup4.add(jRDataVisualizar);
        jRDataVisualizar.setText("Data");
        jRDataVisualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRDataVisualizarMouseClicked(evt);
            }
        });

        jCBDiaFinal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dia", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30" }));

        buttonGroup4.add(jRPesoVisualizar);
        jRPesoVisualizar.setText("Peso");
        jRPesoVisualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRPesoVisualizarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(jBVisualizar))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLDataFianl)
                                .addComponent(jLDataInicial)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jRCodigoVisualizar)
                                .addGap(18, 18, 18)
                                .addComponent(jRTipoVisualizar)
                                .addGap(18, 18, 18)
                                .addComponent(jRPesoVisualizar)
                                .addGap(18, 18, 18)
                                .addComponent(jRDataVisualizar)
                                .addGap(18, 18, 18)
                                .addComponent(jRStatusVisualizar))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jCBDiaFinal, 0, 67, Short.MAX_VALUE)
                                    .addComponent(jCBDiaInicial, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jCBMesInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCBMesFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jCBAnoFinal, 0, 80, Short.MAX_VALUE)
                                    .addComponent(jCBAnoInicial, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jRCodigoVisualizar)
                    .addComponent(jRTipoVisualizar)
                    .addComponent(jRPesoVisualizar)
                    .addComponent(jRDataVisualizar)
                    .addComponent(jRStatusVisualizar))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLDataInicial)
                    .addComponent(jCBDiaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCBMesInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCBAnoInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLDataFianl)
                    .addComponent(jCBDiaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCBMesFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCBAnoFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jBVisualizar)
                .addContainerGap())
        );

        jTabelaVisualizar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Tipo", "Peso", "Ano-Mes-Dia", "Status"
            }
        ));
        jScrollPane2.setViewportView(jTabelaVisualizar);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPVisualizarLayout = new javax.swing.GroupLayout(jPVisualizar);
        jPVisualizar.setLayout(jPVisualizarLayout);
        jPVisualizarLayout.setHorizontalGroup(
            jPVisualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPVisualizarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPVisualizarLayout.setVerticalGroup(
            jPVisualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPVisualizarLayout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Visualizar Rebanho", jPVisualizar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBCadastrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBCadastrarMouseClicked
        
        String aux;
        String temp, list[];
        temp = jCBMesCadastro.getSelectedItem().toString();
        list = temp.split("-");
        aux = (jCBAnoCadastro.getSelectedItem().toString() + "-" + list[0] + "-" +  jCBDiaCadastro.getSelectedItem().toString());
 
        try {
            Class.forName("org.postgresql.Driver");
            conn = DriverManager.getConnection(url, user, pws);
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        } catch (SQLException ex1) {
            JOptionPane.showMessageDialog(rootPane, ex1);
        }
        if(jRGadoDeCorteCadastro.isSelected())
        {
            cmd = "InSERT INTO gadosteste2(codidentificacao,tipo,peso,dataaquisicao,status) "
                    + "VALUES('"+jTCodigoDeIdentificacaoCadastro.getText()+"',"
                    + "' Gado de Corte ','"+jTPesoCadastro.getText()+"','"+aux
                    +"',"+"' Disponível')";
        try {
                      
            stm = conn.createStatement();
            stm.executeUpdate(cmd);
            JOptionPane.showMessageDialog(rootPane, "Registro inserido com sucesso");
            jTCodigoDeIdentificacaoCadastro.setText("");
            jTPesoCadastro.setText("");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        }
        }
        
        if(jRGadoDeLeiteCadastro.isSelected())
        {
            cmd = "InSERT INTO gadosteste2(codidentificacao,tipo,peso,dataaquisicao,status) "
                    + "VALUES('"+jTCodigoDeIdentificacaoCadastro.getText()+"',"
                    + "' Gado de Leite ','"+jTPesoCadastro.getText()+"','"+aux
                    +"',"+"' Disponível')";  
        try {
                      
            stm = conn.createStatement();
            stm.executeUpdate(cmd);
            JOptionPane.showMessageDialog(rootPane, "Registro inserido com sucesso");
            jTCodigoDeIdentificacaoCadastro.setText("");
            jTPesoCadastro.setText("");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        }
        }
        
    }//GEN-LAST:event_jBCadastrarMouseClicked

    private void jBPesquisarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBPesquisarMouseClicked

        try {
            Class.forName("org.postgresql.Driver");
            conn = DriverManager.getConnection(url, user, pws);
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        } catch (SQLException ex1) {
            JOptionPane.showMessageDialog(rootPane, ex1);
        }
        
        jLSelecaoCodIdenCBAtualizar.setVisible(true);
        jCBCodIdenAtualizar.setVisible(true);
        jLOu.setVisible(true);
        jLCodigoDeIdentificacaoAtualizar.setVisible(true);
        jTCodIdentAtualizar.setVisible(true);
        jBPesquisar.setVisible(true);
        jTabelaAtualizar.setVisible(true);
        jLAtualizar.setVisible(true);
        jRPeso.setVisible(true);
        jRStatus.setVisible(true);
        jTAtualizar.setVisible(true);
        jBAtualizar.setVisible(true);
        
        tabela = (DefaultTableModel) jTabelaAtualizar.getModel();
        tabela.setNumRows(0);
        cmd = "SELECT * from gadosteste2 ORDER BY codIdentificacao";
        try {
            stm = conn.createStatement();
            returnquery = stm.executeQuery(cmd);
            boolean verificar = false;
            while(returnquery.next()){
                if(jTCodIdentAtualizar.getText().isEmpty())
                {
                    
                    if(returnquery.getString("codIdentificacao").equalsIgnoreCase(jCBCodIdenAtualizar.getSelectedItem().toString()))
                    {
                        jLAviso1.setText("");
                        tabela.addRow(new Object[]{returnquery.getString("codIdentificacao"),returnquery.getString("tipo"),
                            returnquery.getString("peso"),returnquery.getString("status")});
                        verificar = true;
                    }
                }else
                {
                    if(returnquery.getString("codIdentificacao").equalsIgnoreCase(jTCodIdentAtualizar.getText()))
                    {
                        jLAviso1.setText("");
                        tabela.addRow(new Object[]{returnquery.getString("codIdentificacao"),returnquery.getString("tipo"),
                        returnquery.getString("peso"),returnquery.getString("status")});
                        jTCodIdentAtualizar.setText("");
                        verificar = true;
                    }
                    
                }    
            }
            if (!verificar){
                jLAviso1.setText("Código inválido");
                jTCodIdentAtualizar.setText("");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        }    
        
    }//GEN-LAST:event_jBPesquisarMouseClicked

    private void jBAtualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBAtualizarMouseClicked
//         TODO add your handling code here:
        if(jRPeso.isSelected())
        {   
            try {
                Class.forName("org.postgresql.Driver");
                conn = DriverManager.getConnection(url, user, pws);
            } catch (ClassNotFoundException ex) {
                JOptionPane.showMessageDialog(rootPane, ex);
            } catch (SQLException ex1) {
                JOptionPane.showMessageDialog(rootPane, ex1);
            }
            cmd = "UPDATE gadosteste2 SET peso ="+jTAtualizar.getText()+" where codIdentificacao ='"+tabela.getValueAt(0, 0)+"'";
            try {
                stm = conn.createStatement();
                stm.executeUpdate(cmd);
                JOptionPane.showMessageDialog(rootPane, "Registro atualizado com sucesso");
                jTCodigoDeIdentificacaoCadastro.setText("");
                jTAtualizar.setText("");
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(rootPane, ex);
                
        }
        }
        if(jRStatus.isSelected())
        {
          try {
                Class.forName("org.postgresql.Driver");
                conn = DriverManager.getConnection(url, user, pws);
            } catch (ClassNotFoundException ex) {
                JOptionPane.showMessageDialog(rootPane, ex);
            } catch (SQLException ex1) {
                JOptionPane.showMessageDialog(rootPane, ex1);
            }
            cmd = "UPDATE gadosteste2 SET status ='"+ jTAtualizar.getText()+"' where codIdentificacao ='"+tabela.getValueAt(0, 0)+"'";
            try {
                stm = conn.createStatement();
                stm.executeUpdate(cmd);
                JOptionPane.showMessageDialog(rootPane, "Registro atualizado com sucesso");
                jTCodigoDeIdentificacaoCadastro.setText("");
                jTAtualizar.setText("");
                
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(rootPane, ex);  
        }
        }
    }//GEN-LAST:event_jBAtualizarMouseClicked

    private void jTabbedPane2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane2MouseClicked
        // TODO add your handling code here:
        if(jTabbedPane2.getSelectedComponent().equals(jPAtualizar))
        {
        jLSelecaoCodIdenCBAtualizar.setVisible(true);
        jCBCodIdenAtualizar.setVisible(true);
        jLOu.setVisible(true);
        jLCodigoDeIdentificacaoAtualizar.setVisible(true);
        jTCodIdentAtualizar.setVisible(true);
        jBPesquisar.setVisible(true);
        jTabelaAtualizar.setVisible(false);
        jLAtualizar.setVisible(false);
        jRPeso.setVisible(false);
        jRStatus.setVisible(false);
        jTAtualizar.setVisible(false);
        jBAtualizar.setVisible(false);
        
        try {
            Class.forName("org.postgresql.Driver");
            conn = DriverManager.getConnection(url, user, pws);
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        } catch (SQLException ex1) {
            JOptionPane.showMessageDialog(rootPane, ex1);
        }
        jCBCodIdenAtualizar.removeAllItems();
        try {
            cmd = "SELECT * from gadosteste2 ORDER BY codIdentificacao";
            stm = conn.createStatement();
            returnquery = stm.executeQuery(cmd);
            while(returnquery.next()){
                jCBCodIdenAtualizar.addItem(returnquery.getString("codIdentificacao"));
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        } catch (Exception e){
            JOptionPane.showMessageDialog(rootPane, e);
        }
        }
        
        if(jTabbedPane2.getSelectedComponent().equals(jPVisualizar))
        {
            jLDataInicial.setVisible(false);
            jLDataFianl.setVisible(false);
            jCBDiaInicial.setVisible(false);
            jCBMesInicial.setVisible(false);
            jCBAnoInicial.setVisible(false);
            jCBDiaFinal.setVisible(false);
            jCBMesFinal.setVisible(false);
            jCBAnoFinal.setVisible(false);
            try {
            Class.forName("org.postgresql.Driver");
            conn = DriverManager.getConnection(url, user, pws);
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        } catch (SQLException ex1) {
            JOptionPane.showMessageDialog(rootPane, ex1);
        }
            tabela = (DefaultTableModel) jTabelaVisualizar.getModel();
            tabela.setNumRows(0);
            if(jRCodigoVisualizar.isSelected()){
                cmd = "SELECT * from gadosteste2 ORDER BY codIdentificacao";
                try {
                stm = conn.createStatement();
                returnquery = stm.executeQuery(cmd);
                while(returnquery.next()){
                    tabela.addRow(new Object[]{returnquery.getString("codIdentificacao"),returnquery.getString("tipo"),
                                returnquery.getString("peso"),returnquery.getString("dataAquisicao"),returnquery.getString("status")});
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(rootPane, ex);
            }
            }    
        }
    }//GEN-LAST:event_jTabbedPane2MouseClicked

    private void jBVisualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBVisualizarMouseClicked
        // TODO add your handling code here:
        try {
            Class.forName("org.postgresql.Driver");
            conn = DriverManager.getConnection(url, user, pws);
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        } catch (SQLException ex1) {
            JOptionPane.showMessageDialog(rootPane, ex1);
        }
        tabela = (DefaultTableModel) jTabelaVisualizar.getModel();
        tabela.setNumRows(0);
        if(jRCodigoVisualizar.isSelected()){
                cmd = "SELECT * from gadosteste2 ORDER BY codIdentificacao";
                try {
                stm = conn.createStatement();
                returnquery = stm.executeQuery(cmd);
                while(returnquery.next()){
                    tabela.addRow(new Object[]{returnquery.getString("codIdentificacao"),returnquery.getString("tipo"),
                                returnquery.getString("peso"),returnquery.getString("dataAquisicao"),returnquery.getString("status")});
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(rootPane, ex);
            }
            }
        if(jRTipoVisualizar.isSelected())
            {
                cmd = "SELECT * from gadosteste2 ORDER BY tipo";
                try {
                stm = conn.createStatement();
                returnquery = stm.executeQuery(cmd);
                while(returnquery.next()){
                    tabela.addRow(new Object[]{returnquery.getString("codIdentificacao"),returnquery.getString("tipo"),
                                returnquery.getString("peso"),returnquery.getString("dataAquisicao"),returnquery.getString("status")});
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(rootPane, ex);
            }
            }
        if(jRPesoVisualizar.isSelected()){
                cmd = "SELECT * from gadosteste2 ORDER BY peso";
                try {
                stm = conn.createStatement();
                returnquery = stm.executeQuery(cmd);
                while(returnquery.next()){
                    tabela.addRow(new Object[]{returnquery.getString("codIdentificacao"),returnquery.getString("tipo"),
                                returnquery.getString("peso"),returnquery.getString("dataAquisicao"),returnquery.getString("status")});
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(rootPane, ex);
            }
            }
        if(jRStatusVisualizar.isSelected()){
                cmd = "SELECT * from gadosteste2 ORDER BY status";
                try {
                stm = conn.createStatement();
                returnquery = stm.executeQuery(cmd);
                while(returnquery.next()){
                    tabela.addRow(new Object[]{returnquery.getString("codIdentificacao"),returnquery.getString("tipo"),
                                returnquery.getString("peso"),returnquery.getString("dataAquisicao"),returnquery.getString("status")});
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(rootPane, ex);
            }
            }
        if(jRDataVisualizar.isSelected()){
            ResultSet registroPorData;
            String temp1, temp2, list1[], list2[];
                    temp1 = jCBMesInicial.getSelectedItem().toString();
                    list1 = temp1.split("-");
                    String data1 = jCBAnoInicial.getSelectedItem().toString() + "-" + list1[0] + "-" + jCBDiaInicial.getSelectedItem().toString();
                    temp2 = jCBMesFinal.getSelectedItem().toString();
                    list2 = temp2.split("-");
                    String data2 = jCBAnoFinal.getSelectedItem().toString() + "-" + list2[0] + "-" + jCBDiaFinal.getSelectedItem().toString();
            if (!data1.equals("Ano-Mes-Dia") && data2.equals("Ano-Mes-Dia")){
            cmd = "SELECT * from gadosteste2 where dataAquisicao >= '" + data1 + "' ORDER BY dataAquisicao";
            try {
                stm = conn.createStatement();
                registroPorData = (stm.executeQuery(cmd));  
                while(registroPorData.next()){
                    tabela.addRow(new Object[]{registroPorData.getString("codIdentificacao"),registroPorData.getString("tipo"),
                                registroPorData.getString("peso"),registroPorData.getString("dataAquisicao"),registroPorData.getString("status")});
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
        }
        else if (data1.equals("Ano-Mes-Dia") && !data2.equals("Ano-Mes-Dia")){
            cmd = "SELECT * from gadosteste2 where dataAquisicao <= '" + data2 + "' ORDER BY dataAquisicao";
            try {
                stm = conn.createStatement();
                registroPorData = (stm.executeQuery(cmd)); 
                while(registroPorData.next()){
                    tabela.addRow(new Object[]{registroPorData.getString("codIdentificacao"),registroPorData.getString("tipo"),
                                registroPorData.getString("peso"),registroPorData.getString("dataAquisicao"),registroPorData.getString("status")});
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
        }
        else{
            cmd = "SELECT * from gadosteste2 where dataAquisicao between '" + data1 + "' and '" + data2 + "' ORDER BY dataAquisicao";
            try {
                stm = conn.createStatement();
                registroPorData = (stm.executeQuery(cmd)); 
                while(registroPorData.next()){
                    tabela.addRow(new Object[]{registroPorData.getString("codIdentificacao"),registroPorData.getString("tipo"),
                                registroPorData.getString("peso"),registroPorData.getString("dataAquisicao"),registroPorData.getString("status")});
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
        }
            }
    }//GEN-LAST:event_jBVisualizarMouseClicked

    
    private void jRDataVisualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRDataVisualizarMouseClicked
        // TODO add your handling code here:
        jLDataInicial.setVisible(true);
        jLDataFianl.setVisible(true);
        jCBDiaInicial.setVisible(true);
        jCBMesInicial.setVisible(true);
        jCBAnoInicial.setVisible(true);
        jCBDiaFinal.setVisible(true);
        jCBMesFinal.setVisible(true);
        jCBAnoFinal.setVisible(true);
    }//GEN-LAST:event_jRDataVisualizarMouseClicked

    private void jRCodigoVisualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRCodigoVisualizarMouseClicked
        // TODO add your handling code here:
            jLDataInicial.setVisible(false);
            jLDataFianl.setVisible(false);
            jCBDiaInicial.setVisible(false);
            jCBMesInicial.setVisible(false);
            jCBAnoInicial.setVisible(false);
            jCBDiaFinal.setVisible(false);
            jCBMesFinal.setVisible(false);
            jCBAnoFinal.setVisible(false);
    }//GEN-LAST:event_jRCodigoVisualizarMouseClicked

    private void jRTipoVisualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRTipoVisualizarMouseClicked
        // TODO add your handling code here:
            jLDataInicial.setVisible(false);
            jLDataFianl.setVisible(false);
            jCBDiaInicial.setVisible(false);
            jCBMesInicial.setVisible(false);
            jCBAnoInicial.setVisible(false);
            jCBDiaFinal.setVisible(false);
            jCBMesFinal.setVisible(false);
            jCBAnoFinal.setVisible(false);
    }//GEN-LAST:event_jRTipoVisualizarMouseClicked

    private void jRPesoVisualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRPesoVisualizarMouseClicked
        // TODO add your handling code here:
            jLDataInicial.setVisible(false);
            jLDataFianl.setVisible(false);
            jCBDiaInicial.setVisible(false);
            jCBMesInicial.setVisible(false);
            jCBAnoInicial.setVisible(false);
            jCBDiaFinal.setVisible(false);
            jCBMesFinal.setVisible(false);
            jCBAnoFinal.setVisible(false);
    }//GEN-LAST:event_jRPesoVisualizarMouseClicked

    private void jRStatusVisualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRStatusVisualizarMouseClicked
        // TODO add your handling code here:
            jLDataInicial.setVisible(false);
            jLDataFianl.setVisible(false);
            jCBDiaInicial.setVisible(false);
            jCBMesInicial.setVisible(false);
            jCBAnoInicial.setVisible(false);
            jCBDiaFinal.setVisible(false);
            jCBMesFinal.setVisible(false);
            jCBAnoFinal.setVisible(false);
    }//GEN-LAST:event_jRStatusVisualizarMouseClicked

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GadosGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GadosGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GadosGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GadosGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GadosGUI().setVisible(true);
            }
        });
    }

    private String cmd;
    private String pws = "jpcn2503";
    private String user = "postgres";
    private String url = "jdbc:postgresql://localhost:5433/ProjetoFinal";
    private ResultSet returnquery; 
    private Connection conn; 
    private Statement stm; 
    private DefaultTableModel tabela;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JButton jBAtualizar;
    private javax.swing.JButton jBCadastrar;
    private javax.swing.JButton jBPesquisar;
    private javax.swing.JButton jBVisualizar;
    private javax.swing.JComboBox<String> jCBAnoCadastro;
    private javax.swing.JComboBox<String> jCBAnoFinal;
    private javax.swing.JComboBox<String> jCBAnoInicial;
    private javax.swing.JComboBox<String> jCBCodIdenAtualizar;
    private javax.swing.JComboBox<String> jCBDiaCadastro;
    private javax.swing.JComboBox<String> jCBDiaFinal;
    private javax.swing.JComboBox<String> jCBDiaInicial;
    private javax.swing.JComboBox<String> jCBMesCadastro;
    private javax.swing.JComboBox<String> jCBMesFinal;
    private javax.swing.JComboBox<String> jCBMesInicial;
    private javax.swing.JLabel jLAtualizar;
    private javax.swing.JLabel jLAviso1;
    private javax.swing.JLabel jLCodigoDeIdentificacaoAtualizar;
    private javax.swing.JLabel jLCodigoDeIdentificacaoCadastro;
    private javax.swing.JLabel jLDataCadastro;
    private javax.swing.JLabel jLDataFianl;
    private javax.swing.JLabel jLDataInicial;
    private javax.swing.JLabel jLOu;
    private javax.swing.JLabel jLPesoCadastro;
    private javax.swing.JLabel jLSelecaoCodIdenCBAtualizar;
    private javax.swing.JLabel jLTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPAtualizar;
    private javax.swing.JPanel jPCadastro;
    private javax.swing.JPanel jPVisualizar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JRadioButton jRCodigoVisualizar;
    private javax.swing.JRadioButton jRDataVisualizar;
    private javax.swing.JRadioButton jRGadoDeCorteCadastro;
    private javax.swing.JRadioButton jRGadoDeLeiteCadastro;
    private javax.swing.JRadioButton jRPeso;
    private javax.swing.JRadioButton jRPesoVisualizar;
    private javax.swing.JRadioButton jRStatus;
    private javax.swing.JRadioButton jRStatusVisualizar;
    private javax.swing.JRadioButton jRTipoVisualizar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTAtualizar;
    private javax.swing.JTextField jTCodIdentAtualizar;
    private javax.swing.JTextField jTCodigoDeIdentificacaoCadastro;
    private javax.swing.JTextField jTPesoCadastro;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTabelaAtualizar;
    private javax.swing.JTable jTabelaVisualizar;
    // End of variables declaration//GEN-END:variables
}
