/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIs;


import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;




/**
 *
 * @author joaopcandido
 */
public class VendasGUI extends javax.swing.JInternalFrame {

    /**
     * Creates new form VendasGUI
     */
    public VendasGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jColorChooser1 = new javax.swing.JColorChooser();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedVendas = new javax.swing.JTabbedPane();
        jPLeite = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jCAnoLeite = new javax.swing.JComboBox<>();
        jLPrecoLitro = new javax.swing.JLabel();
        jTPrecoLitro = new javax.swing.JTextField();
        jCMesLeite = new javax.swing.JComboBox<>();
        jCDiaLeite = new javax.swing.JComboBox<>();
        jBVenderLeite = new javax.swing.JButton();
        jTQuantLitros = new javax.swing.JTextField();
        jLDataLeite = new javax.swing.JLabel();
        jLQuantLitros = new javax.swing.JLabel();
        jLCompradorLeite = new javax.swing.JLabel();
        jTCompradorLeite = new javax.swing.JTextField();
        jPCorte = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jTQuantKg = new javax.swing.JTextField();
        jTPrecoKg = new javax.swing.JTextField();
        jLPrecoKg = new javax.swing.JLabel();
        jTCompradorCorte = new javax.swing.JTextField();
        jLCompradorCorte = new javax.swing.JLabel();
        jTIdCorte = new javax.swing.JTextField();
        jLIdCorte = new javax.swing.JLabel();
        jLDataCorte = new javax.swing.JLabel();
        jLQuantKg = new javax.swing.JLabel();
        jCMesCorte = new javax.swing.JComboBox<>();
        jBVenderCorte = new javax.swing.JButton();
        jCAnoCorte = new javax.swing.JComboBox<>();
        jCDiaCorte = new javax.swing.JComboBox<>();
        jPRelatorio = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableRegistroVendas = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jCFiltrarDia1 = new javax.swing.JComboBox<>();
        jLFiltrarData1 = new javax.swing.JLabel();
        jTFiltrarComprador = new javax.swing.JTextField();
        jCFiltrarDia2 = new javax.swing.JComboBox<>();
        jLFiltrar = new javax.swing.JLabel();
        jCFiltrarAno1 = new javax.swing.JComboBox<>();
        jLFiltrarCodigo = new javax.swing.JLabel();
        jRBCorte = new javax.swing.JRadioButton();
        jBPesquisar = new javax.swing.JButton();
        jRBLeite = new javax.swing.JRadioButton();
        jLFiltrarData2 = new javax.swing.JLabel();
        jLFiltrarComprador = new javax.swing.JLabel();
        jTFiltrarCodigo = new javax.swing.JTextField();
        jCFiltrarAno2 = new javax.swing.JComboBox<>();
        jCFiltrarMes2 = new javax.swing.JComboBox<>();
        jCFiltrarMes1 = new javax.swing.JComboBox<>();

        jMenu1.setText("jMenu1");

        jFormattedTextField1.setText("jFormattedTextField1");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximizable(true);
        setResizable(true);
        setTitle("Vendas");

        jTabbedVendas.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jTabbedVendas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedVendasMouseClicked(evt);
            }
        });

        jCAnoLeite.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030" }));

        jLPrecoLitro.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLPrecoLitro.setText("Preço por litro:");

        jCMesLeite.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01- Janeiro", "02- Fevereiro", "03- Março", "04- Abril", "05- Maio", "06- Junho", "07- Julho", "08- Agosto", "09- Setembro", "10- Outubro", "11- Novembro", "12- Dezembro" }));

        jCDiaLeite.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        jBVenderLeite.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jBVenderLeite.setText("Vender");
        jBVenderLeite.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBVenderLeiteMouseClicked(evt);
            }
        });

        jLDataLeite.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLDataLeite.setText("Data:");

        jLQuantLitros.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLQuantLitros.setText("Quantidade (em litros):");

        jLCompradorLeite.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLCompradorLeite.setText("Comprador:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLCompradorLeite)
                            .addGap(18, 18, 18)
                            .addComponent(jTCompradorLeite, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(137, 137, 137)
                                    .addComponent(jLDataLeite)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jCDiaLeite, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jCMesLeite, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jCAnoLeite, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLPrecoLitro)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTPrecoLitro, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(105, 105, 105)
                                    .addComponent(jLQuantLitros)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTQuantLitros, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(224, 224, 224)
                        .addComponent(jBVenderLeite, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTCompradorLeite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLCompradorLeite))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLPrecoLitro)
                    .addComponent(jLQuantLitros)
                    .addComponent(jTPrecoLitro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTQuantLitros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLDataLeite)
                    .addComponent(jCDiaLeite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCMesLeite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCAnoLeite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addComponent(jBVenderLeite)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPLeiteLayout = new javax.swing.GroupLayout(jPLeite);
        jPLeite.setLayout(jPLeiteLayout);
        jPLeiteLayout.setHorizontalGroup(
            jPLeiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPLeiteLayout.createSequentialGroup()
                .addContainerGap(104, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(109, Short.MAX_VALUE))
        );
        jPLeiteLayout.setVerticalGroup(
            jPLeiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPLeiteLayout.createSequentialGroup()
                .addContainerGap(101, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(135, Short.MAX_VALUE))
        );

        jTabbedVendas.addTab("Leite", jPLeite);

        jLPrecoKg.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLPrecoKg.setText("Preço por arroba:");

        jLCompradorCorte.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLCompradorCorte.setText("Comprador:");

        jLIdCorte.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLIdCorte.setText("Cod. de Identificação:");

        jLDataCorte.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLDataCorte.setText("Data:");

        jLQuantKg.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLQuantKg.setText("Quantidade (em arroba):");

        jCMesCorte.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01- Janeiro", "02- Fevereiro", "03- Março", "04- Abril", "05- Maio", "06- Junho", "07- Julho", "08- Agosto", "09- Setembro", "10- Outubro", "11- Novembro", "12- Dezembro" }));

        jBVenderCorte.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jBVenderCorte.setText("Vender");
        jBVenderCorte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBVenderCorteMouseClicked(evt);
            }
        });

        jCAnoCorte.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030" }));

        jCDiaCorte.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLCompradorCorte)
                            .addGap(18, 18, 18)
                            .addComponent(jTCompradorCorte, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLPrecoKg)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTPrecoKg, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLDataCorte)
                                    .addGap(6, 6, 6)
                                    .addComponent(jCDiaCorte, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jCMesCorte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jCAnoCorte, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLIdCorte)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTIdCorte, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLQuantKg)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTQuantKg, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(227, 227, 227)
                        .addComponent(jBVenderCorte, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTCompradorCorte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLCompradorCorte))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLPrecoKg)
                    .addComponent(jLQuantKg)
                    .addComponent(jTPrecoKg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTQuantKg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLIdCorte)
                    .addComponent(jTIdCorte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLDataCorte)
                    .addComponent(jCDiaCorte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCMesCorte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCAnoCorte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addComponent(jBVenderCorte)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPCorteLayout = new javax.swing.GroupLayout(jPCorte);
        jPCorte.setLayout(jPCorteLayout);
        jPCorteLayout.setHorizontalGroup(
            jPCorteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPCorteLayout.createSequentialGroup()
                .addContainerGap(110, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );
        jPCorteLayout.setVerticalGroup(
            jPCorteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCorteLayout.createSequentialGroup()
                .addContainerGap(99, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(131, Short.MAX_VALUE))
        );

        jTabbedVendas.addTab("Corte", jPCorte);

        jTableRegistroVendas.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jTableRegistroVendas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Transação", "Produto", "Cod. Animal", "Quantidade", "$ / unidade", "Total", "Comprador", "Ano-Mes-Dia"
            }
        ));
        jTableRegistroVendas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableRegistroVendasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableRegistroVendas);

        jCFiltrarDia1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dia", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        jLFiltrarData1.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLFiltrarData1.setText("De:");

        jTFiltrarComprador.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N

        jCFiltrarDia2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dia", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        jLFiltrar.setFont(new java.awt.Font("Noto Sans", 0, 16)); // NOI18N
        jLFiltrar.setText("Filtrar Registro:");

        jCFiltrarAno1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ano", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030" }));

        jLFiltrarCodigo.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLFiltrarCodigo.setText("Cod. Animal:");

        jRBCorte.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jRBCorte.setText("Corte");

        jBPesquisar.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jBPesquisar.setText("Filtrar");
        jBPesquisar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBPesquisarMouseClicked(evt);
            }
        });

        jRBLeite.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jRBLeite.setText("Leite");

        jLFiltrarData2.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLFiltrarData2.setText("Até:");

        jLFiltrarComprador.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLFiltrarComprador.setText("Comprador:");

        jTFiltrarCodigo.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N

        jCFiltrarAno2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ano", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030" }));

        jCFiltrarMes2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mes", "01- Janeiro", "02- Fevereiro", "03- Março", "04- Abril", "05- Maio", "06- Junho", "07- Julho", "08- Agosto", "09- Setembro", "10- Outubro", "11- Novembro", "12- Dezembro" }));

        jCFiltrarMes1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mes", "01- Janeiro", "02- Fevereiro", "03- Março", "04- Abril", "05- Maio", "06- Junho", "07- Julho", "08- Agosto", "09- Setembro", "10- Outubro", "11- Novembro", "12- Dezembro" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLFiltrar)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRBLeite)
                            .addComponent(jRBCorte))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLFiltrarData1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCFiltrarDia1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCFiltrarMes1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCFiltrarAno1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLFiltrarData2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCFiltrarDia2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCFiltrarMes2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCFiltrarAno2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLFiltrarComprador)
                            .addComponent(jLFiltrarCodigo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTFiltrarCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFiltrarComprador, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(326, 326, 326)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLFiltrar)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRBLeite)
                    .addComponent(jCFiltrarDia1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCFiltrarMes1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCFiltrarAno1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLFiltrarData1)
                    .addComponent(jLFiltrarComprador)
                    .addComponent(jTFiltrarComprador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRBCorte)
                    .addComponent(jLFiltrarData2)
                    .addComponent(jCFiltrarDia2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCFiltrarMes2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCFiltrarAno2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLFiltrarCodigo)
                    .addComponent(jTFiltrarCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jBPesquisar)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPRelatorioLayout = new javax.swing.GroupLayout(jPRelatorio);
        jPRelatorio.setLayout(jPRelatorioLayout);
        jPRelatorioLayout.setHorizontalGroup(
            jPRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPRelatorioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 763, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPRelatorioLayout.setVerticalGroup(
            jPRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPRelatorioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedVendas.addTab("Relatório Compradores", jPRelatorio);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedVendas)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedVendas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBVenderLeiteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBVenderLeiteMouseClicked
        // TODO add your handling code here:
        database = new VendasBD();
        database.conectar();
        String temp, list[];
        temp = jCMesLeite.getSelectedItem().toString();
        list = temp.split("-");
        data = jCAnoLeite.getSelectedItem().toString() + "-" + list[0] + "-" + jCDiaLeite.getSelectedItem().toString();
        database.inserirDados("Leite", "-", Float.parseFloat(jTQuantLitros.getText()), 
                Float.parseFloat(jTPrecoLitro.getText()), jTCompradorLeite.getText(), data);
        database.desconectar();
        jTQuantLitros.setText("");
        jTPrecoLitro.setText("");
        jTCompradorLeite.setText("");
        
    }//GEN-LAST:event_jBVenderLeiteMouseClicked

    private void jBVenderCorteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBVenderCorteMouseClicked
        // TODO add your handling code here:
        database = new VendasBD();
        database.conectar();
        String temp, list[];
        temp = jCMesCorte.getSelectedItem().toString();
        list = temp.split("-");
        data = jCAnoCorte.getSelectedItem().toString() + "-" + list[0] + "-" + jCDiaCorte.getSelectedItem().toString();
        database.inserirDados("Corte", jTIdCorte.getText(), Float.parseFloat(jTQuantKg.getText()), 
                Float.parseFloat(jTPrecoKg.getText()), jTCompradorCorte.getText(), data);
        database.desconectar();
        jTQuantKg.setText("");
        jTPrecoKg.setText("");
        jTCompradorCorte.setText("");
        jTIdCorte.setText("");
    }//GEN-LAST:event_jBVenderCorteMouseClicked

    private void jTabbedVendasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedVendasMouseClicked
        // TODO add your handling code here:
        DefaultTableModel tabela = (DefaultTableModel) jTableRegistroVendas.getModel();
        tabela.setNumRows(0);
        if(jTabbedVendas.getSelectedComponent().equals(jPRelatorio)){
            database = new VendasBD();
            database.conectar();
            database.verRegistro();
            registro = database.getReturnquery();
            try {
                while (registro.next()){
                    tabela.addRow(new Object[]{registro.getString("id"), registro.getString("produto"), registro.getString("idanimal"),
                    registro.getString("quantidade"), registro.getString("preco"), registro.getString("total"),
                    registro.getString("comprador"), registro.getString("data")});
                }
            } catch (SQLException ex) {
                Logger.getLogger(VendasGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
            database.desconectar();
        }
    }//GEN-LAST:event_jTabbedVendasMouseClicked

    private void jBPesquisarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBPesquisarMouseClicked
        // TODO add your handling code here:
        DefaultTableModel tabela = (DefaultTableModel) jTableRegistroVendas.getModel();
        tabela.setNumRows(0);
        ResultSet registroPorData;
        database = new VendasBD();
        database.conectar();
        boolean filtrar = false;
        try {
            database.verRegistro();
            registro = database.getReturnquery();
            while (registro.next()){
                if (jRBCorte.isSelected()){
                    if (registro.getString("produto").equals("Corte")){
                        tabela.addRow(new Object[]{registro.getString("id"), registro.getString("produto"), registro.getString("idanimal"),
                            registro.getString("quantidade"), registro.getString("preco"), registro.getString("total"),
                            registro.getString("comprador"), registro.getString("data")});
                        filtrar = true;
                    }
                }
                if (jRBLeite.isSelected()){
                    if (registro.getString("produto").equals("Leite")){
                        tabela.addRow(new Object[]{registro.getString("id"), registro.getString("produto"), registro.getString("idanimal"),
                            registro.getString("quantidade"), registro.getString("preco"), registro.getString("total"),
                            registro.getString("comprador"), registro.getString("data")});
                        filtrar = true;
                    }
                }
                if (!jTFiltrarComprador.getText().equals("")){
                    if (registro.getString("comprador").contains(jTFiltrarComprador.getText())){
                        tabela.addRow(new Object[]{registro.getString("id"), registro.getString("produto"), registro.getString("idanimal"),
                                registro.getString("quantidade"), registro.getString("preco"), registro.getString("total"),
                                registro.getString("comprador"), registro.getString("data")});
                            filtrar = true;
                    }
                }
                if (!jTFiltrarCodigo.getText().equals("")){
                    if (registro.getString("idanimal").contains(jTFiltrarCodigo.getText())){
                        tabela.addRow(new Object[]{registro.getString("id"), registro.getString("produto"), registro.getString("idanimal"),
                                registro.getString("quantidade"), registro.getString("preco"), registro.getString("total"),
                                registro.getString("comprador"), registro.getString("data")});
                            filtrar = true;
                    }
                }
            }
            if ((!jCFiltrarAno1.getSelectedItem().toString().equals("Ano") && !jCFiltrarMes1.getSelectedItem().toString().equals("Mes") && !jCFiltrarDia1.getSelectedItem().toString().equals("Dia"))
                            || (!jCFiltrarAno2.getSelectedItem().toString().equals("Ano") && !jCFiltrarMes2.getSelectedItem().toString().equals("Mes") && !jCFiltrarDia2.getSelectedItem().toString().equals("Dia"))){
                    String temp1, temp2, list1[], list2[];
                    temp1 = jCFiltrarMes1.getSelectedItem().toString();
                    list1 = temp1.split("-");
                    String data1 = jCFiltrarAno1.getSelectedItem().toString() + "-" + list1[0] + "-" + jCFiltrarDia1.getSelectedItem().toString();
                    temp2 = jCFiltrarMes2.getSelectedItem().toString();
                    list2 = temp2.split("-");
                    String data2 = jCFiltrarAno2.getSelectedItem().toString() + "-" + list2[0] + "-" + jCFiltrarDia2.getSelectedItem().toString();
                    database.registroPorData(data1, data2);
                    registroPorData = database.getReturndata();
                    System.out.println(data1);
                    System.out.println(data2);
                    while (registroPorData.next()){
                        tabela.addRow(new Object[]{registroPorData.getString("id"), registroPorData.getString("produto"), registroPorData.getString("idanimal"),
                            registroPorData.getString("quantidade"), registroPorData.getString("preco"), registroPorData.getString("total"),
                            registroPorData.getString("comprador"), registroPorData.getString("data")});
                    }
                    filtrar = true;
            }            
            if (!filtrar){
                database.verRegistro();
                registro = database.getReturnquery();
                try {
                    while (registro.next()){
                        tabela.addRow(new Object[]{registro.getString("id"), registro.getString("produto"), registro.getString("idanimal"),
                        registro.getString("quantidade"), registro.getString("preco"), registro.getString("total"),
                        registro.getString("comprador"), registro.getString("data")});
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(VendasGUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(VendasGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        database.desconectar();
    }//GEN-LAST:event_jBPesquisarMouseClicked

    private void jTableRegistroVendasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableRegistroVendasMouseClicked
        // TODO add your handling code here:
        System.out.println(jTableRegistroVendas.getSelectedColumn());
    }//GEN-LAST:event_jTableRegistroVendasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VendasGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VendasGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VendasGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VendasGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VendasGUI().setVisible(true);
            }
        });
    }
    
private VendasBD database;
private ResultSet registro;
private String data;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jBPesquisar;
    private javax.swing.JButton jBVenderCorte;
    private javax.swing.JButton jBVenderLeite;
    private javax.swing.JComboBox<String> jCAnoCorte;
    private javax.swing.JComboBox<String> jCAnoLeite;
    private javax.swing.JComboBox<String> jCDiaCorte;
    private javax.swing.JComboBox<String> jCDiaLeite;
    private javax.swing.JComboBox<String> jCFiltrarAno1;
    private javax.swing.JComboBox<String> jCFiltrarAno2;
    private javax.swing.JComboBox<String> jCFiltrarDia1;
    private javax.swing.JComboBox<String> jCFiltrarDia2;
    private javax.swing.JComboBox<String> jCFiltrarMes1;
    private javax.swing.JComboBox<String> jCFiltrarMes2;
    private javax.swing.JComboBox<String> jCMesCorte;
    private javax.swing.JComboBox<String> jCMesLeite;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLCompradorCorte;
    private javax.swing.JLabel jLCompradorLeite;
    private javax.swing.JLabel jLDataCorte;
    private javax.swing.JLabel jLDataLeite;
    private javax.swing.JLabel jLFiltrar;
    private javax.swing.JLabel jLFiltrarCodigo;
    private javax.swing.JLabel jLFiltrarComprador;
    private javax.swing.JLabel jLFiltrarData1;
    private javax.swing.JLabel jLFiltrarData2;
    private javax.swing.JLabel jLIdCorte;
    private javax.swing.JLabel jLPrecoKg;
    private javax.swing.JLabel jLPrecoLitro;
    private javax.swing.JLabel jLQuantKg;
    private javax.swing.JLabel jLQuantLitros;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPCorte;
    private javax.swing.JPanel jPLeite;
    private javax.swing.JPanel jPRelatorio;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRBCorte;
    private javax.swing.JRadioButton jRBLeite;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTCompradorCorte;
    private javax.swing.JTextField jTCompradorLeite;
    private javax.swing.JTextField jTFiltrarCodigo;
    private javax.swing.JTextField jTFiltrarComprador;
    private javax.swing.JTextField jTIdCorte;
    private javax.swing.JTextField jTPrecoKg;
    private javax.swing.JTextField jTPrecoLitro;
    private javax.swing.JTextField jTQuantKg;
    private javax.swing.JTextField jTQuantLitros;
    private javax.swing.JTabbedPane jTabbedVendas;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTableRegistroVendas;
    // End of variables declaration//GEN-END:variables
}
